Add Simple Factory Pattern implementation
iluwatar/java-design-patterns pull request #1516
Opened 2020-09-02 12:58 UTC by samilAyoub

Java source code demonstrate simple factory design pattern.

relates to : #1477

2020-09-03 14:43 UTC, iluwatar requested changes
`README.md` is missing

2020-09-03 14:43 UTC, iluwatar commented on pom.xml
> +        <module>simple-factory</module>
Please use the name `factory`

2020-09-03 14:43 UTC, iluwatar commented on simple-factory/src/main/java/com/iluwatar/simplefactory/App.java
> +
Please describe here the pattern in few sentences and how this example implements it. See the other patterns for examples.

2020-09-03 14:43 UTC, iluwatar commented on simple-factory/src/main/java/com/iluwatar/simplefactory/App.java
> +    Car car1 = CarSimpleFactory.getCar(CarSimpleFactory.CarType.FORD);
Please use local variable type inference `var` where possible

2020-09-03 21:33 UTC, samilAyoub commented
@iluwatar I dont know why urm-maven-plugin generates factory.urm.puml but does not genertaes factory.urm.png?

2020-09-03 21:43 UTC, samilAyoub commented on pom.xml
> +        <module>simple-factory</module>
Done

2020-09-04 10:09 UTC, ravening commented
One suggestion which I can say is to use Lambda expressions instead of using switch cases to generate Cars.
You can refer to an example in https://github.com/ravening/Lambda-Expressions_java/tree/master/designpatterns/rv/factory

2020-09-04 10:11 UTC, ravening commented on factory/pom.xml
> +			<!-- Maven assembly plugin is invoked with default setting which we have
Better to use spaces instead of tabs

2020-09-04 21:03 UTC, samilAyoub commented on factory/pom.xml
> +			<!-- Maven assembly plugin is invoked with default setting which we have
Done

2020-09-04 21:18 UTC, samilAyoub commented on factory/pom.xml
> +			<!-- Maven assembly plugin is invoked with default setting which we have
@ravening Done !

2020-09-04 21:23 UTC, samilAyoub commented on factory/pom.xml
> +			<!-- Maven assembly plugin is invoked with default setting which we have
@ravening please review the changes.

2020-09-05 13:02 UTC, iluwatar commented
> @iluwatar I don't know why urm-maven-plugin generates factory.urm.puml but does not generates factory.urm.png?

It doesn't, the image needs to be created by hand. See https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2020-09-05 13:10 UTC, iluwatar requested changes

2020-09-05 13:10 UTC, iluwatar commented on factory/README.md
> +We have an interface "Car" and tow implementations "Ford" and "Ferrari".
```suggestion
We have an interface `Car` and two implementations `Ford` and `Ferrari`.
```

2020-09-05 13:10 UTC, iluwatar commented on factory/README.md
> +Then we have the static method "getCar" to create car objects encapsulated in the factory class "CarSimpleFactory".
```suggestion
Then we have the static method `getCar` to create car objects encapsulated in the factory class `CarSimpleFactory`.
```

2020-09-05 13:10 UTC, iluwatar commented on factory/README.md
> +The code becomes more complicated than it should be.
We could rephrase this part a bit so that there is ##Applicability section and under it `Pros` and `Cons`.

2020-09-05 13:10 UTC, iluwatar commented on factory/README.md
> +The code becomes more complicated than it should be.
Additionally please add a class diagram.

2020-09-06 16:28 UTC, iluwatar commented on factory/README.md
> +We have an interface 'Car' and tow implementations 'Ford' and 'Ferrari'.
```suggestion
We have an interface `Car` and tow implementations `Ford` and `Ferrari`.
```

2020-09-06 16:28 UTC, iluwatar commented on factory/README.md
> +We have an interface "Car" and tow implementations "Ford" and "Ferrari".
Still not ok

2020-09-06 16:31 UTC, iluwatar approved these changes

2020-09-06 16:31 UTC, iluwatar commented on factory/README.md
> +## Pros
```suggestion
Pros
```

2020-09-06 16:31 UTC, iluwatar commented on factory/README.md
> +## Cons
```suggestion
Cons
```

2020-09-06 16:32 UTC, iluwatar commented
Found just minor issues so I'll merge it and push a change after it.

2020-09-06 16:33 UTC, merged

2020-09-06 16:35 UTC, iluwatar commented
Many thanks for the new pattern! 

@all-contributors please add @samilAyoub for code

2020-09-06 16:36 UTC, iluwatar commented
@all-contributors please add @ravening for review