Refactor the command pattern to use lambda functions
iluwatar/java-design-patterns pull request #1531
Opened 2020-10-01 00:02 UTC by ravening

We can leverage the lambda expressions of Java 8 onwards
to implement a command design pattern instead of traditional
non-functional way

In the traditional way, we usually have a `Command` interface and the concrete commands implement this interface
This interface will have one abstract function called `execute`
So each concrete command has to override just one function to achieve the functionality.

We know that if any interface just has one abstract method then it can be used a functional interface and can be passed around as lambda expression instead of instantiating it.

Fixes #1468

2020-10-10 14:54 UTC, iluwatar requested changes
Additionally, please merge the changes from `master` branch to make the pull request build pass.

2020-10-10 14:54 UTC, iluwatar commented on command/src/main/java/com/iluwatar/command/App.java
>   * receiver. Values for parameters of the receiver method are stored in the command. The receiver
> Values for parameters of the receiver method are stored in the command.

I think this does not hold true anymore

2020-10-10 14:54 UTC, iluwatar commented on command/src/main/java/com/iluwatar/command/Goblin.java
> +  }
Any reason why we shouldn't put these methods in `Target` class instead?

2020-10-10 14:54 UTC, iluwatar commented on command/src/main/java/com/iluwatar/command/Goblin.java
> +  }
Javadocs like this don't add much value

2020-10-13 15:38 UTC, ravening commented
> Additionally, please merge the changes from `master` branch to make the pull request build pass.

@iluwatar made changes. Please review again

2020-11-08 17:33 UTC, iluwatar approved these changes

2020-11-08 17:33 UTC, merged

2020-11-08 17:34 UTC, iluwatar commented
Thanks @ravening, this looks very good!