Added page factory design pattern
iluwatar/java-design-patterns pull request #1552
Opened 2020-10-09 13:08 UTC by osandadeshan

Pull request title

- Clearly and concisely describes what it does
- Refer to the issue that it solves, if available

Pull request description

- Describes the main changes that come with the pull request
- Any relevant additional information is provided

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2020-11-07 12:45 UTC, iluwatar commented
@osandadeshan since this change comes from outside our issue list, can you say where this testing pattern has been best described?

2020-11-07 15:14 UTC, osandadeshan commented
@iluwatar It is actually a test automation design pattern vastly used in the industry.
https://www.browserstack.com/guide/page-object-model-in-selenium

2020-12-09 05:47 UTC, ohbus requested changes

2020-12-09 05:47 UTC, ohbus commented on page-factory/pom.xml
> +</project>
add an empty line at the end of the file

2020-12-09 05:57 UTC, ohbus reviewed
I cannot seem to understand one thing which is everywhere in the web _(including the reference that you have provided in the comment)_ mentions the pattern to be called as **Page Object Model** whereas you have used the term **Page Factory** design pattern.

Please clarify on the above point to help me understand you better.

Thank you.

2020-12-09 05:59 UTC, ohbus commented
> I cannot seem to understand one thing which is everywhere in the web _(including the reference that you have provided in the comment)_ mentions the pattern to be called as **Page Object Model** whereas you have used the term **Page Factory** design pattern.
> 
> Please clarify on the above point to help me understand you better.
> 
> Thank you.

@osandadeshan  What I understand from the above perspective that **Page Factory Design Pattern** is **Enhanced POM**
but on which ground.

2020-12-09 10:23 UTC, osandadeshan commented
Selenium's PageFactory, is simply an annotation that serves to delegate to Selenium the instantiation of some WebElement objects you might want to have on an object that represents a web page or a component.

As mentioned on the [Selenium documentation](https://github.com/SeleniumHQ/selenium/wiki/PageObjects):

**`There is a PageFactory in the support package that provides support for this pattern, and helps to remove some boiler-plate code from your Page Objects at the same time.`**

PageFactory serves to make things more succinct, it does not implement the Page Object design pattern out-of-the-box.

2020-12-09 13:01 UTC, tomaszwojciechowski commented
PageFactory is not a design pattern. The design pattern is Page Object, while PageFactory is a class in the Selenium framework that supports the Page Object pattern by removing the boilerplate code from the Page Object classes, instantiating those classes and setting up a lazy proxy for WebElement and List \<WebElement\> fields.

2020-12-09 19:17 UTC, iluwatar commented
I agree with @tomaszwojciechowski. We already have Page Object pattern, see https://github.com/iluwatar/java-design-patterns/issues/229.

2021-01-02 04:21 UTC, closed without merging