Aditi
iluwatar/java-design-patterns pull request #1555
Opened 2020-10-10 21:42 UTC by aditi2906

Pull request title

changes in content and code

2020-10-11 06:56 UTC, ohbus requested changes

2020-10-11 06:56 UTC, ohbus commented on .all-contributorsrc
> +
No need to add this.
Our bot will handle this once your PR gets merged into the codebase.

2020-10-11 06:56 UTC, ohbus commented on abstract-factory/src/main/java/com/iluwatar/abstractfactory/Army.java
> +   String getDescription();
No need for a change here
This file is formatted in two space for each tab.

2020-10-11 06:56 UTC, ohbus commented on abstract-factory/src/main/java/com/iluwatar/abstractfactory/ElfArmy.java
> +  static final String DESCRIPTION = "This is the Eleven Army!";
It is Elven and not Eleven.
The context here is not a number.

2020-10-11 06:56 UTC, ohbus commented on abstract-factory/src/main/java/com/iluwatar/abstractfactory/Kingdom.java
> +    this.king = King;
This is violating the principles of writing variables and methods.

Find the relevant information in our [developer wiki](https://github.com/iluwatar/java-design-patterns/wiki)

2020-10-11 06:56 UTC, ohbus commented on abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcKingdom.java
> +}
Add a line after a file ends

2020-10-11 06:56 UTC, ohbus commented on abstract-factory/src/main/java/com/iluwatar/abstractfactory/OrcKingdomFactory.java
> +  }
Please explain this in the PR description.

2020-10-11 06:56 UTC, ohbus commented on event-queue/src/main/java/com/iluwatar/event/queue/Audio.java
> +      return null;
@iluwatar your comments on this please.

2020-10-11 06:56 UTC, ohbus commented on event-queue/src/main/java/com/iluwatar/event/queue/Audio.java
> +    return PendingAudio;
No need to change this.
Please follow the design guidelines.

2020-10-11 06:56 UTC, ohbus commented on event-queue/src/main/java/com/iluwatar/event/queue/PlayMessage.java
> +    return Volume;
Follow the guidelines of writing Java code.

2020-11-07 18:14 UTC, iluwatar commented
@aditi2906 These changes do not help. Please see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

@ohbus thanks for reviewing

2020-11-07 18:14 UTC, closed without merging