Updated Java 8 lambda functions
iluwatar/java-design-patterns pull request #1574
Opened 2020-10-17 17:02 UTC by Tubaleviao

Fixes #1469

I added parameters and return values to the classes to show a little more about the advantages of using the Strategy Pattern. Plus I added the lambda functions to the README file .

2020-10-17 18:38 UTC, Tubaleviao commented
The error coming from Java PR Builder is the following:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project strategy: You have 32 Checkstyle violations. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :strategy
Error: Process completed with exit code 1.
```

I have no idea what this is and I guess I'll need to format my computer since I deleted my AppData folder and my buildPath in Eclipse went crazy.

2020-10-19 17:18 UTC, viveksb007 commented
@Tubaleviao there are check-style issues in your PR. Have a look here https://github.com/iluwatar/java-design-patterns/wiki/03.-Coding-conventions and fix the check-style issues.

2020-12-01 15:58 UTC, ravening commented on strategy/README.md
> +
Remove unnecessary spaces

2020-12-01 16:11 UTC, ravening commented
@Tubaleviao This PR is still not using the lambda functions efficiently.
You can avoid all the unwanted classes by replacing them with Enums. Then by using the enum value you can change your strategy.

```
enum Strategy {
    Melee(myfunction),
    Projectile(<pass a function here>)
   //remaning strategies

  private Function<T,R> function;

  Strategy(Function<T,R> f) {
    this.function = f;
  }

  // getters and others
  Function<T,R> getFunction() {
    return this.function;
  }
}
```

Define function like
```
String myfunction(Integer n) {
    return "MeleeStrategy: With your Excalibur you cut dragon's leg "+n+" times!";
}
```

Once you have this enum you can use the enum values to get output

```
LOGGER.info(Strategy.Melee.getFunction().apply(5));
```

2020-12-29 08:47 UTC, iluwatar requested changes

2020-12-29 08:47 UTC, iluwatar commented on strategy/README.md
> +    return "MeleeStrategy: With your Excalibur you cut dragon's leg "+n+" times!";
Prefer `String.format` instead of concatenating

2020-12-29 08:47 UTC, iluwatar commented on strategy/README.md
> +    return "MeleeStrategy: With your Excalibur you cut dragon's leg "+n+" times!";
Check this elsewhere too

2020-12-29 08:47 UTC, iluwatar commented on strategy/README.md
> +    LOGGER.info("************ Java 8 Strategy pattern ************");
Could we say "Java 8 lambda based Strategy pattern"?

2020-12-29 08:47 UTC, iluwatar commented on strategy/README.md
> +    LOGGER.info("************ Java 8 Strategy pattern ************");
Check this in the code too

2020-12-29 08:47 UTC, iluwatar commented on strategy/src/test/java/com/iluwatar/strategy/DragonSlayingStrategyTest.java
> +    //assertEquals(1, appender.getLogSize());
This line should be either uncommented or removed

2020-12-29 08:47 UTC, iluwatar commented on strategy/src/test/java/com/iluwatar/strategy/DragonSlayingStrategyTest.java
> +    //}
This block should be removed?

2020-12-29 08:47 UTC, iluwatar commented on strategy/src/test/java/com/iluwatar/strategy/DragonSlayingStrategyTest.java
> +    //}
This block should be removed?

2021-03-07 16:31 UTC, ohbus commented
@Tubaleviao It would be very kind of you if you could please confirm if you are working on this repository as we did not see any updates from you regarding the comments and the changes that has been requested.

This PR has been inactive for a long time, we will close it soon if we do not see any updates from your side.

2021-03-07 16:53 UTC, Tubaleviao commented
I'm not working on it, you can close it.

2021-03-07 17:13 UTC, ohbus commented
Thank you for letting us know!

2021-03-07 17:13 UTC, closed without merging