api-gateway: some code cleanup
iluwatar/java-design-patterns pull request #1581
Opened 2020-10-24 00:22 UTC by TeodorRussu

api-gateway: some code cleanup

2020-12-03 19:27 UTC, iluwatar requested changes
The build is failing due to Checkstyle errors

2020-12-04 09:56 UTC, ohbus approved these changes

2020-12-04 09:58 UTC, ohbus commented
I cannot confirm the build status.

2020-12-07 03:23 UTC, ohbus commented
@TeodorRussu Can you check the [documentation from here](https://github.com/iluwatar/java-design-patterns/wiki/03.-Coding-conventions#formatting) and update the CheckStyle issue of this PR to get it accepted!

2021-02-02 09:48 UTC, ravening commented on api-gateway/api-gateway-service/src/main/java/com/iluwatar/api/gateway/ApiGateway.java
> +  @GetMapping(path = "/desktop")
you can just do `@GetMapping("/desktop")`

2021-03-07 16:36 UTC, ohbus commented
@TeodorRussu please look into the comments by @ravening as they will mostly be reported by _sonarbot_.

As this PR has been inactive for a long time, we will close it soon if we do not see any updates.

2021-03-23 21:46 UTC, closed without merging

2021-03-23 21:46 UTC, TeodorRussu commented
not today