#1317 Special Case Pattern
iluwatar/java-design-patterns pull request #1624
Opened 2021-01-10 17:14 UTC by ignite1771

This PR implement the e-commerce system referred in the issue as the example for Special Case Pattern. 

To begin with, to focus on the pattern itself, I implement the DB and maintenance lock of the e-commerce system by the singleton instance.

**Use Case**:  When a logged-in user purchases a product, different receipt view model will be showed based on different cases:
- If the transaction is successful, the default receipt will be showed.
- If the transaction is failed, the particular receipt of one of the special cases will be showed, instead of just a null object with no meaning.

To sum up, we encapsulate special cases into subclasses that provide special behaviors of the target returned interface.

2021-01-11 03:47 UTC, ohbus requested changes

2021-01-11 03:47 UTC, ohbus commented on special-case/etc/special-case.urm.puml
> +@enduml
Add a new line

2021-01-11 03:47 UTC, ohbus commented on special-case/pom.xml
> +</project>
Add a new line

2021-01-11 03:47 UTC, ohbus commented on special-case/src/test/java/com/iluwatar/specialcase/AppTest.java
> +}
Add a new line

2021-01-11 04:54 UTC, ignite1771 commented on special-case/src/test/java/com/iluwatar/specialcase/AppTest.java
> +}
Thanks. Solve it in 43a9fab.

2021-01-11 04:54 UTC, ignite1771 commented on special-case/pom.xml
> +</project>
Thanks. Solve it in 43a9fab.

2021-01-11 04:54 UTC, ignite1771 commented on special-case/etc/special-case.urm.puml
> +@enduml
Thanks. Solve it in 43a9fab.

2021-01-11 05:07 UTC, ohbus approved these changes

2021-01-13 07:36 UTC, merged

2021-01-13 07:39 UTC, ohbus commented
@ignite1771 Thank you for contributing to this repository.

It was a great pull request overall.

2021-01-13 07:39 UTC, ohbus commented
@all-contributors please add @ignite1771 for code