#1625 Turkish translation
iluwatar/java-design-patterns pull request #1661
Opened 2021-02-24 23:29 UTC by demirhalil

#1625 

Pull request description

- Turkish translation is added for singleton design pattern

2021-02-25 16:38 UTC, ohbus requested changes
Thank you for your contribution!

Please resolve the conflicts.

2021-02-25 16:38 UTC, ohbus commented on tr/singleton/README.md
> +![alt text](./etc/singleton.urm.png "Singleton pattern class diagram")
Need to change this to the original file.

2021-03-01 10:49 UTC, demirhalil commented
I will close the Pr because I forgot to update the recent changes from master and after merging it in my local, it shows a lot of changes. So will open a new pr for this.

2021-03-01 10:49 UTC, closed without merging

2021-03-01 13:15 UTC, ohbus commented
You do not need to close it. You could have just rebased and force push.

2021-03-01 13:26 UTC, demirhalil commented
It is my first the first open source project that I contribute which is why I did not want to do something wrong. If I have again such situation again, I'll do what you said. Thank you for the suggestion :))