Money Pattern Implementation - Issue #1305
iluwatar/java-design-patterns pull request #1673
Opened 2021-03-11 20:16 UTC by ToxicDreamz

Money Pattern Implementation

- I've implemented the Money pattern, and provided a demonstration of how it can be used.
- This implementation is to showcase how to work with multiple types of currencies.

Pull request description

- There are certain things that I would have done differently within the demonstration aspect of the Money Pattern Implementation, i.e Error Handling, adding more checks to get rid of certain bugs, etc. but at that point I'd probably end up writing a whole banking system. 😂

2021-03-11 20:32 UTC, ToxicDreamz commented
SonarCloud found 2 bugs, which I'll push a fix for.

2021-03-12 02:31 UTC, ohbus requested changes
Along with the bugs reported you also need to mitigate any code smell that it has and more importantly increase code coverage by providing test cases.

2021-03-18 06:09 UTC, iluwatar requested changes

2021-03-18 06:09 UTC, iluwatar commented on money/src/main/java/com/iluwatar/money/Account.java
> +        System.err.println("Insufficient funds in balance.");
Please use a logger for output. See Lombok `@Slf4j` annotation.

2021-03-18 06:09 UTC, iluwatar commented on money/src/main/java/com/iluwatar/money/Account.java
> +        System.err.println("Insufficient funds in balance.");
Check this throughout the example.

2021-03-18 06:09 UTC, iluwatar commented on money/src/main/java/com/iluwatar/money/Balance.java
> +  }
To replace boilerplate such as these getters you're able to use Lombok annotations.

2021-03-18 06:09 UTC, iluwatar commented on money/src/main/java/com/iluwatar/money/exception/BalanceCouldNotBeCreatedException.java
> +}
I'm not sure you need all these constructors. Maybe define only the ones you use?

2021-03-25 08:16 UTC, ToxicDreamz commented
I'll get these issues fixed as soon as possible, I just haven't had any extra time on my hands.

2021-03-25 08:19 UTC, ohbus commented
> I'll get these issues fixed as soon as possible, I just haven't had any extra time on my hands.

No worries. Take your time and just let us know when you'll be able to complete it.

2022-01-06 17:46 UTC, iluwatar commented
Closed due to inactivity

2022-01-06 17:46 UTC, closed without merging