data transfer hash(issue 1269)
iluwatar/java-design-patterns pull request #1704
Opened 2021-04-18 04:51 UTC by x418-22n

finished the design pattern data transfer hash(issue 1269)

2021-04-19 06:59 UTC, ohbus requested changes
You have added the bytecode instead of the actual code.

Please submit the java code re-evaluation.

2021-04-19 06:59 UTC, ohbus commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/Presentation.java
> +
please remove the extra line spaces

2021-04-19 06:59 UTC, ohbus commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/Business.java
> +
remove extra spaces

2021-04-26 07:52 UTC, ohbus requested changes
I wonder why the bytecode is still here and how it managed to get inside git tracking instead of being mentioned in the gitignore 😕 

1. Please take a look into these other patterns for understanding how you would like to design the readme section of the patterns from the examples below besides following the [**Wiki**](https://github.com/iluwatar/java-design-patterns/wiki) section.
    - https://github.com/iluwatar/java-design-patterns/tree/master/abstract-factory
    - https://github.com/iluwatar/java-design-patterns/tree/master/active-object
    - https://github.com/iluwatar/java-design-patterns/tree/master/acyclic-visitor
    - https://github.com/iluwatar/java-design-patterns/tree/master/acyclic-visitor
    - https://github.com/iluwatar/java-design-patterns/tree/master/aggregator-microservices
    - https://github.com/iluwatar/java-design-patterns/tree/master/ambassador
    - https://github.com/iluwatar/java-design-patterns/tree/master/api-gateway
    - https://github.com/iluwatar/java-design-patterns/tree/master/factory-method
    - https://github.com/iluwatar/java-design-patterns/tree/master/flyweight
    - https://github.com/iluwatar/java-design-patterns/tree/master/game-loop
    - https://github.com/iluwatar/java-design-patterns/tree/master/iterator

2. Also add the pattern to the parent pom for it to get executed and perform necessary analysis on your newly submitted code.

If you have any queries or facing difficulties please reach out to me after you have read the [**Wiki**](https://github.com/iluwatar/java-design-patterns/wiki) section properly

2021-05-01 18:19 UTC, iluwatar requested changes

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Folder naming uses snake case. Data_Transfer_Hash -> data_transfer_hash

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/pom.xml
> +  </dependencies>
I think we can remove this part

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/pom.xml
> +    </pluginManagement>
Many of the plugins are already specified in the parent pom.xml. Check how the other pattern pom.xmls have been defined e.g. https://github.com/iluwatar/java-design-patterns/blob/master/abstract-factory/pom.xml

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/readme.md
> + - Performance
I would suggest structural and decoupling. See https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/readme.md
> +title: data transfer hash
```suggestion
title: Data Transfer Hash

```

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/readme.md
> +* data transfer hash
This is the original pattern name, right? No need to specify it here.

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/readme.md
> +Providing a  class called data transfer hash, in order to send message between other class.
The intent should describe the pattern very clearly and concisely. Please try to rephrase.

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/readme.md
> +> https://www.oreilly.com/library/view/j2ee-design-patterns/0596004273/re12.html
Add the link to another section, see https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/App.java
> +A more robust implementation uses a container object to hold the hash, as well as identifying information, type-safe data retrieval methods, and well-known keys.
I would first explain what the pattern is, then how this example implements it

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/App.java
> +        Hash hash= new Hash();
You can use `var` in many occasions, check throughout the example

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/App.java
> +        business.create("a", "aaa", hash);
Please use some time to come up with a more interesting example than 'a' and 'aaa'

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/App.java
> +        System.out.println("Business create "+"aaa");
Use a proper logger, check elsewhere too

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/Business.java
> +    public void create(String k,Object v,Hash hash)
Consider a more descriptive name for the method

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/Business.java
> +    public Object get(String k,Hash hash)
Consider naming

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/Hash.java
> +    public void create(String k,Object v)
Would `put` be a better name?

2021-05-01 18:19 UTC, iluwatar commented on Data_Transfer_Hash/src/main/java/Data_Transfer_Hash/Presentation.java
> +    }
Consider naming

2021-10-09 18:54 UTC, iluwatar commented
@x418-22n please address the review comments

2022-01-16 18:43 UTC, iluwatar commented
Closed due to inactivity

2022-01-16 18:43 UTC, closed without merging