#841 Add Client-Server Pattern
iluwatar/java-design-patterns pull request #1712
Opened 2021-04-22 12:30 UTC by Mediocrity7

- solve issue #841 
- Client-server pattern is a distributed application structure that partitions tasks or workloads between the providers of a resource or service, called servers, and service requesters, called clients.
- This pattern is widely used in E-mail, World Wide Web, etc.

2021-04-22 16:23 UTC, ohbus requested changes
Please increase code coverage by providing test cases and remove the issues reposted by SonarCloud

You can always put the PR to draft if it is not ready for a review and you want to check against the CI

2021-04-25 18:00 UTC, iluwatar requested changes

2021-04-25 18:00 UTC, iluwatar commented on client-server/README.md
> + - Architectural
```suggestion
 - Decoupling
```

2021-04-25 18:00 UTC, iluwatar commented on client-server/README.md
> +- The capacity of the Client and Servers can be changed separately.
```suggestion
Client-server pattern consists of two parties; a server and multiple clients. The server component will provide services to multiple client components. Clients request services from the server and the server provides relevant services to those clients.```

2021-04-25 18:00 UTC, iluwatar commented on client-server/README.md
> +> Email, World Wide Web, etc.
Please provide a bit more verbose example

2021-04-25 18:00 UTC, iluwatar commented on client-server/README.md
> +> Server dispatch resources and clients request them.
```suggestion
> In the client-server pattern the server provides services to multiple clients.
```

2021-04-25 18:00 UTC, iluwatar commented on client-server/README.md
> +* java.net.Socket
Please provide links

2021-04-25 18:00 UTC, iluwatar commented on client-server/README.md
> +* Phishing or capturing login credentials or other useful information of the user are common and MITM(Man in the Middle) attacks are common.
Since these thoughts are all security-related, maybe start the explanation with something like `From the security standpoint...`

2021-04-25 18:00 UTC, iluwatar commented on client-server/src/main/java/com.iluwatar.clientserver/Client.java
> +      e.printStackTrace();
Please use a proper logger. Lombok provides `@Slf4j` annotation for this..

2021-04-26 10:10 UTC, ohbus commented
Thank you so much @iluwatar for the comments!

2021-05-29 08:34 UTC, iluwatar commented
There's a conflict that needs to be resolved. Once you're ready for another review, let us know @Mediocrity7

2022-11-09 19:45 UTC, iluwatar commented
Closed due to inactivity

2022-11-09 19:45 UTC, closed without merging