add table data gateway (issue #1318)
iluwatar/java-design-patterns pull request #1720
Opened 2021-04-25 02:48 UTC by guapi777

add table data gateway pattern (issue #1318)

- Table Data Gateway is a design pattern in which an object acts as a gateway to a database table.[1] The idea is to separate the responsibility of fetching items from a database from the actual usages of those objects. Users of the gateway are then insulated from changes to the way objects are stored in the database.
- issue #1318

Pull request description

- add table data gateway pattern

2021-04-25 06:02 UTC, ohbus requested changes
Please fix the code smells

2021-05-01 17:55 UTC, iluwatar requested changes

2021-05-01 17:55 UTC, iluwatar commented on table-data-gateway/README.md
> +Table Data Gateway is a design pattern in which an object acts as a gateway to a database table. The idea is to separate the responsibility of fetching items from a database from the actual usages of
Add explanation section after intent. Please see the other patterns how it's supposed to be implemented e.g. https://github.com/iluwatar/java-design-patterns/tree/master/abstract-factory

2021-05-01 17:55 UTC, iluwatar commented on table-data-gateway/pom.xml
> +    </properties>
These lines aren't needed

2021-05-01 17:55 UTC, iluwatar commented on table-data-gateway/pom.xml
> +    </dependencies>
Add maven-assembly-plugin to be able to execute the pattern directly from the command line

2021-05-01 17:55 UTC, iluwatar commented on table-data-gateway/src/main/java/com/iluwatar/tabledatagateway/Person.java
> +  private int age;
Utilize Lombok to reduce boilerplate. See https://github.com/iluwatar/java-design-patterns/wiki/18.-Lombok

2021-05-01 17:55 UTC, iluwatar commented on table-data-gateway/src/main/java/com/iluwatar/tabledatagateway/PersonGateWay.java
> +    }
Better throw an exception

2021-05-01 17:55 UTC, iluwatar commented on table-data-gateway/src/main/java/com/iluwatar/tabledatagateway/PersonGateWay.java
> +  public void insert(String firstName, String lastName, String gender, int age) {
It doesn't communicate errors. If something goes wrong, it could return false or throw an exception.

2021-05-03 14:10 UTC, guapi777 commented
OK, I'll fix these. Please give me some time

2022-09-21 17:41 UTC, closed without merging