Add table module pattern
iluwatar/java-design-patterns pull request #1721
Opened 2021-04-25 03:13 UTC by tao-sun2

- Resolves issue #1319 
- In Table Module a single class encapsulates all the domain logic for all records stored in a table or view.
- I use the same scenario which is used in [Transaction Script](https://github.com/iluwatar/java-design-patterns/tree/master/transaction-script) and refactor the code from Transaction Script pattern to Table Module pattern.

2021-04-25 04:54 UTC, tao-sun2 commented
The duplication rate is high because I use the same scenario as Transaction Script and refactor the code from one pattern to another. Should I choose a new scenario and reimplement the example?

2021-04-25 06:00 UTC, ohbus commented
> The duplication rate is high because I use the same scenario as Transaction Script and refactor the code from one pattern to another. Should I choose a new scenario and reimplement the example?

Yes please

2021-04-25 06:04 UTC, ohbus requested changes
While you are already working on fixing the code duplications please ensure that other parameters like **code smells** and **bugs** are also removed in the process.

2021-04-25 06:39 UTC, tao-sun2 commented
I will try to do this.

2021-05-01 14:15 UTC, iluwatar requested changes

2021-05-01 14:15 UTC, iluwatar commented on table-module/src/main/java/com/iluwatar/tablemodule/RoomDaoImpl.java
> +    }
Maybe just let it throw

2021-05-01 14:15 UTC, iluwatar commented on table-module/src/main/java/com/iluwatar/tablemodule/RoomDaoImpl.java
> +    }
Please check the same issue elsewhere too

2021-05-01 14:15 UTC, iluwatar commented on table-module/src/main/java/com/iluwatar/tablemodule/RoomTableModule.java
> +      throw new Exception("Room number: " + roomNumber + " does not exist");
It's bad practice to throw generic exceptions. I think we should create our own room booking exception class.

2021-05-01 14:15 UTC, iluwatar commented on table-module/src/main/java/com/iluwatar/tablemodule/RoomTableModule.java
> +        LOGGER.info(refundAmount + " is refunded");
Combine into single logging line

2021-05-01 14:15 UTC, iluwatar commented on table-module/src/main/java/com/iluwatar/tablemodule/RoomDao.java
> +public interface RoomDao {
Could we use some other name for the classes not to confuse with the DAO pattern?

2021-05-02 15:24 UTC, closed without merging

2021-05-02 15:52 UTC, tao-sun2 commented
I am deeply sorry that I closed this pull request and create a new pull request for the same issue #1319  because I reimplement the Table Module pattern instead of refactoring the code from Transaction Script pattern to Table Module pattern. The link for the new pull request is https://github.com/iluwatar/java-design-patterns/pull/1742

2021-05-04 17:51 UTC, iluwatar commented
@tao-sun2 although you closed this pull request, please consider the review comments in the new PR. I would not want to do the same work again.