foreign-key
iluwatar/java-design-patterns pull request #1723
Opened 2021-04-25 07:25 UTC by lanxiang1234

Foreign-Key-Mapping

- Maps an association between objects to a foreign key reference between tables.

- Each object contains the database key from the appropriate database table. If two objects are linked together with an association, this association can be replaced by a foreign key in the database.

Pull request description

- tests and three class

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2021-04-25 08:20 UTC, lanxiang1234 commented
Foreign Key Mapping pattern #1296

2021-05-01 17:45 UTC, iluwatar requested changes

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/README.md
> +- foreign-key
The available categories and tags are listed in https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags. If not necessary, please don't make new ones. I suggest we use `Structural` category and `Data access` tag.

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/README.md
> +- The table containing the foreign key is called the child table, and the table containing the candidate key is called the referenced or parent table.
I suggest we put the key points under separate header. The available headers are listed in https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template.

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/README.md
> +
Add explanation section here. See the other patterns how it's implemented, for example https://github.com/iluwatar/java-design-patterns/tree/master/abstract-factory

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/pom.xml
> +    </properties>
I don't think these are needed. They are specified in the parent pom.xml

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/pom.xml
> +        </dependency>
Add maven-assembly-plugin to enable executing the pattern directly from the command line

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/src/main/java/com/iluwatar/foreignkey/Album.java
> + * CS304 Issue link: https://github.com/iluwatar/java-design-patterns/issues/1296
I don't think the issue link is needed here

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/src/main/java/com/iluwatar/foreignkey/Album.java
> +  private Artist artist;
Use Lombok annotations to reduce boilerplate. See https://github.com/iluwatar/java-design-patterns/wiki/18.-Lombok

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/src/main/java/com/iluwatar/foreignkey/Album.java
> + * CS304 Issue link: https://github.com/iluwatar/java-design-patterns/issues/1296
Check elsewhere too

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/src/main/java/com/iluwatar/foreignkey/App.java
> + */
Add here a brief explanation of how the example implements the pattern

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/src/main/java/com/iluwatar/foreignkey/Album.java
> +  private Artist artist;
Check other classes too

2021-05-01 17:45 UTC, iluwatar commented on foreign-key-mapping/src/test/java/com/iluwatar/foreignkey/ArtistTest.java
> +    String t = "artist" + Integer.toString(1);
You can variable type inference (var keyword) in many places

2021-05-01 17:45 UTC, iluwatar commented on identity-field/README.md
> +categories: Object-Relational Structural
```suggestion
categories: Structural
```

2021-05-01 17:45 UTC, iluwatar commented on identity-field/README.md
> +- Identity-Field
```suggestion
- Data access
```

2021-05-01 17:45 UTC, iluwatar commented on identity-field/README.md
> +- Generate your own
Move these under separate heading and add explanation section

2021-05-01 17:45 UTC, iluwatar commented on identity-field/pom.xml
> +        </dependency>
Add maven-assembly-plugin

2021-05-01 17:45 UTC, iluwatar commented on identity-field/pom.xml
> +    </properties>
Remove this part

2021-05-01 17:45 UTC, iluwatar commented on identity-field/src/main/java/com/iluwatar/identityfield/App.java
> + * The type App.
Explain here how the sample implements the pattern

2021-05-01 17:45 UTC, iluwatar commented on identity-field/src/main/java/com/iluwatar/identityfield/App.java
> +    List<Person> pearsonList = new LinkedList<>();
Use var

2021-05-01 17:45 UTC, iluwatar commented on identity-field/src/main/java/com/iluwatar/identityfield/Person.java
> +  private String name;
Use Lombok

2021-05-21 13:59 UTC, lanxiang1234 commented
ok im going to change these problems

2022-09-21 17:50 UTC, closed without merging