Fixed pages showing up in wrong language
iluwatar/java-design-patterns pull request #1750
Opened 2021-05-09 18:41 UTC by JackieNim

Fix issue where links show up in the wrong language
https://github.com/iluwatar/java-design-patterns-web/issues/22

2021-05-11 19:31 UTC, ohbus requested changes
Kindly take a look at the comments.

2021-05-11 19:38 UTC, JackieNim commented on fr/README.md
> +Ce projet est concédé sous les termes de la licence MIT.
I think there was a problem when I tired forking the project 🤔 Let me try again

2021-05-11 20:02 UTC, JackieNim commented on fr/README.md
> +Ce projet est concédé sous les termes de la licence MIT.
@ohbus https://github.com/iluwatar/java-design-patterns/pull/1752 is the new PR

2021-05-11 20:03 UTC, closed without merging

2021-05-14 10:52 UTC, iluwatar commented
> @iluwatar We may need to update the Wiki for the same changes we will be proposing to help new contributors and old ones as well to get familiarized with the new standard of adding language selection.

Good point @ohbus. I created a new issue https://github.com/iluwatar/java-design-patterns/issues/1755 about this.

2021-05-14 15:28 UTC, ohbus commented
@iluwatar Shall we reopen #1752 against this and re-review the whole doc again?

Or is there any way that you know where @JackieNim can rrecoverthis deleted fork to make [this PR](https://github.com/iluwatar/java-design-patterns/pull/1750) open again?

2021-05-14 15:34 UTC, iluwatar commented
Since the repository has been deleted I don't know any other way than reopening #1752