#394 add collector-state pattern
iluwatar/java-design-patterns pull request #1769
Opened 2021-05-21 12:05 UTC by Laurels7

Resolve issue#394

The main intention is to manage sequence of events of same type. For example, a Call object needs to collect all the digits to perform call routing. This will involve activities like a timer start before each digit, digit collection, timer stop at each digit collection, timeout on complete digit collection and call routing on complete digit collection.

2021-05-22 07:46 UTC, Mediocrity7 commented
Oops...Seems like this guy has already made some progress. Maybe I should find other issue to fix. Good luck. @Laurels7

2021-06-01 19:57 UTC, iluwatar requested changes
Thanks for the pull request! There are multiple issues to be resolved. Please look at the review comments. Additionally, there are some extra .class files that should be removed. Test coverage is also insufficient at this point.

2021-06-01 19:57 UTC, iluwatar commented on collector-state/README.md
> +---
Add `language: en`

2021-06-01 19:57 UTC, iluwatar commented on collector-state/README.md
> +---
I can't find a good match from the existing tags, but it would be nice to have one..

2021-06-01 19:57 UTC, iluwatar commented on collector-state/README.md
> +
```suggestion
## Explanation
```

2021-06-01 19:57 UTC, iluwatar commented on collector-state/README.md
> +
Add programmatic example here

2021-06-01 19:57 UTC, iluwatar commented on collector-state/collector-state.iml
> +</module>
Remove this file

2021-06-01 19:57 UTC, iluwatar commented on collector-state/pom.xml
> +        </dependency>
We use SonarCloud for static analysis, so we should get rid of this dependency.

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/App.java
> + * with self-defined message and states.
Describe the pattern briefly and then explain how the pattern is implemented in this example

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/App.java
> +    int minimumDigit = 2;
You can use `var` for these too

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/App.java
> +    LOGGER.info(collectorState.getDescription());
Add comments to explain what is going on

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/DigitCollectorState.java
> +  }
Use Lombok getter

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/App.java
> +    var m = new StateMachine();
It feels strange to have the state machine outside the DigitCollectorState. Maybe it should be baked in?

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/DigitMsg.java
> +}
I think it's kind of convoluted to have a single message that keeps a read pointer. We should probably move the example towards having many small stateless messages.

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/StateMachine.java
> +  String[] digits = new String[capacity];
What are these fields used for?

2021-06-01 19:57 UTC, iluwatar commented on collector-state/src/main/java/com/iluwatar/collectorstate/App.java
> +    }
I don't approve that we have a single message passed to the collectorState multiple times. I think we should use some kind of threaded messaging that sends multiple stateless messages instead.

2022-09-21 18:09 UTC, closed without merging