Added FanOut/FanIn Pattern
iluwatar/java-design-patterns pull request #1787
Opened 2021-06-16 06:11 UTC by karthikbhat13

FanOut/FanIn Pattern

- The pattern refers to executing multiple instances of the activity function on multiple chunks in parallel
- Resolved iluwatar#1627

Pull request description
- Added code that implements the design pattern and test cases

2021-06-20 08:49 UTC, iluwatar requested changes
Thanks for implementing this pattern. Looks good in general. I added some improvement requests, please take a look and let us know when you're ready for another review.

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +title: FanOut-FanIn
```suggestion
title: Fan-Out/Fan-In 
```

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +categories: Concurrency
```suggestion
categories: Integration
```

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +- Performance
```suggestion
- Microservices
```

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +process the individual return value from activity function as they are done running into a final result.
The term activity function is not self-explanatory. Could we perhaps talk about microservices?

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +process the individual return value from activity function as they are done running into a final result.
We should also explain how the caller eventually gets the aggregated result.

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +process the individual return value from activity function as they are done running into a final result.
We need an explanation section and some of the details could be placed there.

2021-06-20 08:49 UTC, iluwatar commented on fanout-fanin/README.md
> +
I think we could add a related patterns section, see https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template. Some of the microservices patterns we already have seemed to be quite similar.

2021-07-09 07:44 UTC, merged

2021-07-09 07:52 UTC, iluwatar commented
@karthikbhat13 I'm not sure what has happened, but the PR doesn't have any changed files anymore. Can you please take a look at it?

2021-07-09 07:59 UTC, karthikbhat13 commented
Oh, didn't notice that. Lemme check. There is a hook to auto pull master branch to base repo. It probably replaced my branch. I will update again.

2021-07-09 08:06 UTC, karthikbhat13 commented
@iluwatar Can I update this PR only to have the changes again? I can't figure it out. For now, I created one more PR, https://github.com/iluwatar/java-design-patterns/pull/1799

Let me know what I can do. Thanks

2021-07-09 08:15 UTC, iluwatar commented
@karthikbhat13 either way, but please ensure that you have addressed my earlier review comments.

2021-07-09 08:24 UTC, karthikbhat13 commented
> @karthikbhat13 either way, but please ensure that you have addressed my earlier review comments.

@iluwatar Have done that. I have fixed the comments and added the explanation and related patterns sections. https://github.com/iluwatar/java-design-patterns/pull/1799/commits/1948342f4f423cbeba5bedac9efa04ffc7168d02 of https://github.com/iluwatar/java-design-patterns/pull/1799

2021-07-09 08:36 UTC, iluwatar commented
Ok, let's continue the process in #1799.

2021-07-09 17:13 UTC, karthikbhat13 commented
> Ok, let's continue the process in #1799.

@iluwatar There was the issue of pull bot again in this PR too. I have create a new one with custom branch,  https://github.com/iluwatar/java-design-patterns/pull/1800. Please consider this whenever convenient.