#1667: Fixing the serverless tests to use Junit5 and execute
iluwatar/java-design-patterns pull request #1794
Opened 2021-06-28 13:32 UTC by tan31989

This issue fixes #1667

Here is what changed:

- Added JUnit5 libraries for serverless
- Removed the s3 SDK exclusions for serverless dependencies
- Replaced the deprecated `MockitoAnnotations.initMocks(this)` with `MockitoAnnotations.openMocks(this)`

2021-06-30 11:36 UTC, ohbus reviewed
I believe the tests are not being executed.

Please check it out and remove the sonar code smells as well.

2021-07-02 06:35 UTC, tan31989 commented
Thanks, @ohbus. I have fixed the Sonar Code smells

Regarding the tests not getting executed, I could see in that it says those tests are part of `mvn clean install`. Here is the link to [first build](https://github.com/iluwatar/java-design-patterns/pull/1794/checks?sha=1d11c137de85bf564bdec8ce0481fd8bbc8da895)

The snippet for tests which was executed:
```sh
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.475 s - in com.iluwatar.serverless.baas.api.SavePersonApiHandlerTest
[INFO] Running com.iluwatar.serverless.baas.api.FindPersonApiHandlerTest
11:44:55.154 [main] INFO com.iluwatar.serverless.baas.api.FindPersonApiHandler - id=37e7a1fe-3544-473d-b764-18128f02d72d
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 s - in com.iluwatar.serverless.baas.api.FindPersonApiHandlerTest
```

2021-07-25 12:30 UTC, ohbus requested changes
Though the results of the tests are being correct. I can see a **Parse Exception** for `com.iluwatar.serverless.baas.api.SavePersonApiHandlerTest`.

You can check from [CircleCI](https://circleci.com/api/v1.1/project/github/iluwatar/java-design-patterns/612/output/103/0?file=true&allocation-id=60dea58a3d04e853ef65b327-0-build%2F159F08CF) or [GH **Actions**](https://github.com/iluwatar/java-design-patterns/runs/3039249881#step:6:22406)

_Stacktrace:_
```java
[INFO] Running com.iluwatar.serverless.baas.api.FindPersonApiHandlerTest
05:42:44.534 [main] INFO com.iluwatar.serverless.baas.api.FindPersonApiHandler - id=37e7a1fe-3544-473d-b764-18128f02d72d
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.177 s - in com.iluwatar.serverless.baas.api.FindPersonApiHandlerTest
[INFO] Running com.iluwatar.serverless.baas.api.SavePersonApiHandlerTest
05:42:44.601 [main] ERROR com.iluwatar.serverless.baas.api.SavePersonApiHandler - unable to parse body
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'invalid': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"invalid sample request"; line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:720)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2903)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1949)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:781)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4684)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
	at com.iluwatar.serverless.baas.api.SavePersonApiHandler.handleRequest(SavePersonApiHandler.java:49)
	at com.iluwatar.serverless.baas.api.SavePersonApiHandlerTest.handleRequestSavePersonException(SavePersonApiHandlerTest.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngi [...]

2021-08-02 09:20 UTC, tan31989 commented
@ohbus I verified this, it's a valid exception message for a test that is trying to find a `400` Bad Request error.  

The test case in question is [handleRequestSavePersonException](https://github.com/iluwatar/java-design-patterns/pull/1794/files#diff-bbc7023aa1f79b6e3762af5f2bd264379706a94ec5c72153624d6ec829feef7dR82)

2021-08-18 08:08 UTC, tan31989 commented
@ohbus do let me know if there was something else I missed. Appreciate your time on this!

2021-09-15 06:58 UTC, tan31989 commented
Hi @ohbus, just checking, were you able to look into this?

2021-09-28 16:25 UTC, ohbus commented
Sorry for the delay @tan31989

2021-09-28 16:26 UTC, ohbus approved these changes
LGTM!

Thanks for the clarification.

2021-09-28 18:39 UTC, merged

2021-09-28 18:39 UTC, ohbus commented
@all-contributors please add @tan31989 for code