Added Domain Model pattern
iluwatar/java-design-patterns pull request #1795
Opened 2021-06-28 18:14 UTC by AndriyPyzh

Domain Model pattern

- Resolves issue #1294 
- A Domain Model is an object model of the domain that incorporates both behavior and data.

Description

- Implement domain model pattern 
- corrected main class name in pom.xml of strategy pattern
- minor update of "Related patterns" in readme file of transaction script pattern

2021-06-28 18:33 UTC, tedyoung commented
Domain Model **is not** a Design Pattern, it's a way of modeling and structuring code in complex systems (I'd even say that it's just the right way to do object-oriented programming). Even if it were a pattern, this code directly contradicts the intent by having the "domain objects" directly reference the persistence objects (DAO).

2021-07-10 09:53 UTC, iluwatar commented
> Domain Model **is not** a Design Pattern, it's a way of modeling and structuring code in complex systems (I'd even say that it's just the right way to do object-oriented programming). Even if it were a pattern, this code directly contradicts the intent by having the "domain objects" directly reference the persistence objects (DAO).

@tedyoung thanks for the comment! The domain model is listed as one of the domain logic patterns in Fowler's [Patterns of Enterprise Application Architecture](https://www.amazon.com/Patterns-Enterprise-Application-Architecture-Martin/dp/0321127420/ref=sr_1_1?crid=1Y3ZS7XOAUJNU&dchild=1&keywords=patterns+of+enterprise+application+architecture&qid=1625910501&s=books&sprefix=patterns+of+enter%2Caps%2C266&sr=1-1). I definitely think that it's a valid design pattern, but I also understand the confusion around the terms. For example, the book by Evans, [Domain-Driven Design](https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software-dp-0321125215/dp/0321125215/ref=mt_other?_encoding=UTF8&me=&qid=1625910547) is all about designing domain models for applications. The concept is so important and goes so deep into the core of software development that it may feel like something larger than a design pattern.

2021-07-10 15:20 UTC, iluwatar requested changes

2021-07-10 15:20 UTC, iluwatar commented on domain-model/src/test/java/com/iluwatar/domainmodel/CustomerDaoImplTest.java
> +  void findByNameTest() throws SQLException {
We don't need to have the "test" suffix in the test method names. The test method name should always describe what is being tested.

2021-07-10 15:20 UTC, iluwatar commented on domain-model/src/test/java/com/iluwatar/domainmodel/CustomerDaoImplTest.java
> +  void findByNameTest() throws SQLException {
See some examples here https://stackoverflow.com/questions/155436/unit-test-naming-best-practices

2021-07-11 17:08 UTC, AndriyPyzh commented
@iluwatar thanks for the review! I updated PR according to your suggestions.

2021-07-20 08:56 UTC, iluwatar requested changes
I think it looks good already, but I'd like to change the category and tags for the pattern.

2021-07-20 08:56 UTC, iluwatar commented on domain-model/README.md
> + - Data access
```suggestion
 - Domain
```

2021-07-20 08:56 UTC, iluwatar commented on domain-model/README.md
> +categories: Structural
```suggestion
categories: Architectural
```

2021-07-20 22:13 UTC, AndriyPyzh commented
@iluwatar I committed your changes.

2021-07-22 13:56 UTC, iluwatar approved these changes

2021-07-22 13:58 UTC, merged

2021-07-22 13:59 UTC, iluwatar commented
Thank you for the new pattern!
@all-contributors please add @AndriyPyzh for code