docs: Chinese translations updates (#1706)
iluwatar/java-design-patterns pull request #1797
Opened 2021-07-03 01:48 UTC by tonels

add Chinese translations updates (based issue #1706)

2021-07-03 01:58 UTC, tonels commented
how can i resovle this ? @ohbus

2021-07-11 08:10 UTC, iluwatar requested changes

2021-07-11 08:10 UTC, iluwatar commented on localization/zh/filterer/README.md
> +  tags:
```suggestion
tags:
```

2021-07-11 08:12 UTC, iluwatar commented
Ping @xiaod-dev, if you have time to review this?

2021-07-16 07:23 UTC, xiaod-dev commented
> Ping @xiaod-dev, if you have time to review this?
9999999999999999999999999999ms.
wow. That's lot's of changes. It will take some times to review it.

2021-07-25 02:35 UTC, xiaod-dev requested changes
@tonels
please update the pic path in all files. Cause the directory structure has been changed. It should be like this:
`![alt text](../../../cloud-static-content-hosting/etc/static-content-hosting.png "Static Content Hosting")` .
**Noted that if the pic path are correct, the pics should display normally.**

2022-11-09 19:42 UTC, iluwatar commented
Closed due to inactivity

2022-11-09 19:42 UTC, closed without merging