Translation zh
iluwatar/java-design-patterns pull request #1805
Opened 2021-07-25 03:00 UTC by xiaod-dev

Pull request description

- add language code 
- correct pic path

2021-07-25 03:37 UTC, xiaod-dev commented
@iluwatar 
I found a translation tool https://crowdin.com/, It seems more industrial and provide more Translate efficiently.
It not free, But It shows free of charge for open-source projects.
https://crowdin.com/page/open-source-project-setup-request
The [ethereum ](https://ethereum.org/en/)project  is also using this for translation work.
I think we can think about it.

2021-07-25 12:17 UTC, ohbus requested changes
As you are aware of the recent changes in localization management.

Please update the **permalink** for the following files by removing the `zh` at the end of it.

2021-07-25 12:17 UTC, ohbus commented on localization/zh/builder/README.md
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/caching/README.md
> +![alt text](../../../caching/etc/caching.png "Caching")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/callback/README.md
> +![alt text](../../../callback/etc/callback.png "Callback")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/chain/README.md
> +![alt text](../../../chain/etc/chain.urm.png "Chain of Responsibility class diagram")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/command/README.md
> +![alt text](../../../command/etc/command.png "Command")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/composite/README.md
> +![alt text](../../../composite/etc/composite.urm.png "Composite class diagram")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/converter/README.md
> +![alt text](../../../converter/etc/converter.png "Converter Pattern")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/dao/README.md
> +![alt text](../../../dao/etc/dao.png "Data Access Object")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/facade/README.md
> +![alt text](../../../facade/etc/facade.urm.png "Facade pattern class diagram")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/dirty-flag/README.md
> +![alt text](../../../dirty-flag/etc/dirty-flag.png "Dirty Flag")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/dependency-injection/README.md
> +![alt text](../../../dependency-injection/etc/dependency-injection.png "Dependency Injection")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/delegation/README.md
> +![alt text](../../../delegation/etc/delegation.png "Delegate")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/decorator/README.md
> +![alt text](../../../decorator/etc/decorator.urm.png "Decorator pattern class diagram")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/data-transfer-object/README.md
> +![alt text](../../../data-transfer-object/etc/data-transfer-object.urm.png "data-transfer-object")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/factory-method/README.md
> +![alt text](../../../factory-method/etc/factory-method.urm.png "Factory Method pattern class diagram")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/proxy/README.md
> +![alt text](../../../proxy/etc/proxy.urm.png "Proxy pattern class diagram")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/producer-consumer/README.md
> +![alt text](../../../producer-consumer/etc/producer-consumer.png "Producer Consumer")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/private-class-data/README.md
> +![alt text](../../../private-class-data/etc/private-class-data.png "Private Class Data")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/observer/README.md
> +![alt text](../../../observer/etc/observer.png "Observer")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/iterator/README.md
> +![alt text](../../../iterator/etc/iterator_1.png "Iterator")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/interpreter/README.md
> +![alt text](../../../interpreter/etc/interpreter_1.png "Interpreter")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/state/README.md
> +![alt text](../../../state/etc/state_urm.png "State")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/strategy/README.md
> +![alt text](../../../strategy/etc/strategy_urm.png "Strategy")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/template-method/README.md
> +![alt text](../../../template-method/etc/template_method_urm.png "Template Method")
Please fix the **permalink** for this file

2021-07-25 12:17 UTC, ohbus commented on localization/zh/visitor/README.md
> +![alt text](../../../visitor/etc/visitor_1.png "Visitor")
Please fix the **permalink** for this file

2021-08-01 14:54 UTC, ohbus approved these changes
LGTM

2021-08-01 14:55 UTC, merged

2021-08-08 13:22 UTC, iluwatar commented
> @iluwatar
> I found a translation tool https://crowdin.com/, It seems more industrial and provide more Translate efficiently.
> It not free, But It shows free of charge for open-source projects.
> https://crowdin.com/page/open-source-project-setup-request
> The [ethereum ](https://ethereum.org/en/)project is also using this for translation work.
> I think we can think about it.

@xiaod-dev thanks for the research effort. I agree we should evaluate the tool. I created a new issue https://github.com/iluwatar/java-design-patterns/issues/1809 about it.