Issue#1312
iluwatar/java-design-patterns pull request #1925
Opened 2021-12-10 20:15 UTC by upulindika

Pull request title

- Clearly and concisely describes what it does
- Refer to the issue that it solves, if available

Pull request description

- Describes the main changes that come with the pull request
- Any relevant additional information is provided

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2021-12-14 16:15 UTC, abimarank requested changes

2021-12-14 16:15 UTC, abimarank commented on remote-facade/src/main/java/com/iluwatar/remotefacade/Order.java
> +      System.out.println("Retrieved order: \n" + order);
Care to remove `System.out` statements?

2021-12-14 16:15 UTC, abimarank commented on remote-facade/src/main/java/com/iluwatar/remotefacade/Order.java
> +      e.printStackTrace();
Care to remove `e.printStackTrace();` statements?

2021-12-19 17:29 UTC, iluwatar requested changes
The build is failing due to old version number

2022-11-09 16:58 UTC, iluwatar commented
Closed due to inactivity

2022-11-09 16:58 UTC, closed without merging