add identity field pattern
iluwatar/java-design-patterns pull request #1978
Opened 2022-04-04 12:22 UTC by lkpengcs

In this pull request,

- Add the identity field pattern
- This is related to this [issue](https://github.com/iluwatar/java-design-patterns/issues/1298)

Pull request description

- Implement the identity field pattern according to the given [link](https://www.sourcecodeexamples.net/2018/05/identity-field-pattern.html).

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-06-03 18:35 UTC, ohbus requested changes
Thank you so much for your efforts!

Can you please check the 2 code smells reported by Sonar?

Would love to have a perfect submission with full coverage analysis as well.

2022-06-06 03:53 UTC, lkpengcs commented
hi, I have removed the code smells. As for the coverage, I can have full coverage locally. Not sure about how Sonar checks this.

2022-09-25 14:33 UTC, iluwatar requested changes

2022-09-25 14:33 UTC, iluwatar commented on identity-field/README.md
> +title: Identity-Field
```suggestion
title: Identity Field
```

2022-09-25 14:33 UTC, iluwatar commented on identity-field/pom.xml
> +            <version>1.18.22</version>
Please use the version from the parent pom.xml

2022-09-25 14:33 UTC, iluwatar commented on identity-field/pom.xml
> +            </plugin>
The configuration seems overly verbose. Can you check how maven-assembly-plugin has been configured in the other patterns?

2022-09-25 14:33 UTC, iluwatar commented on identity-field/pom.xml
> +            </plugin>
This should be left out. Use the Java version that's coming from the parent pom.xml (11)

2022-11-08 19:03 UTC, iluwatar commented
Closed due to inactivity

2022-11-08 19:03 UTC, closed without merging