Added Optimistic Concurrency Pattern
iluwatar/java-design-patterns pull request #2006
Opened 2022-05-26 09:02 UTC by JeffersonJefferson-pixel

Pull request title

- Added Optimistic Concurrency Pattern
- fixes #1280

Pull request description

- Implements Optimistic Concurrency Pattern based on provided resource: http://ommolketab.ir/aaf-lib/axkwht7wxrhvgs2aqkxse8hihyu9zv.pdf chapter 10.2
- Also took inspiration from https://www.javacodegeeks.com/2012/11/jpahibernate-version-based-optimistic-concurrency-control.html

2022-09-24 17:07 UTC, iluwatar requested changes

2022-09-24 17:07 UTC, iluwatar commented on optimistic-concurrency/pom.xml
> +    </properties>
Leave out, use the versions that the parent pom.xml specifies

2022-09-24 17:07 UTC, iluwatar commented on optimistic-concurrency/pom.xml
> +            <version>1.0.2.Final</version>
Use the versions from the parent pom.xml

2022-09-24 17:07 UTC, iluwatar commented on optimistic-concurrency/pom.xml
> +    </dependencies>
Add maven-assembly-plugin so we can execute this example from the command line

2022-09-24 17:07 UTC, iluwatar commented on optimistic-concurrency/src/main/java/com/iluwatar/optimisticconcurrency/App.java
> + */
Please add more verbose explanation what the pattern is and how this example implements it

2022-09-24 17:07 UTC, iluwatar commented on optimistic-concurrency/src/main/java/com/iluwatar/optimisticconcurrency/App.java
> +  }
It's very hard to see what is going on in this example without explanation. Please add comments.

2022-11-08 19:09 UTC, closed without merging

2022-11-09 06:51 UTC, mohanaraosv commented
@iluwatar Shall I continue this and give credit to the original Author?

2022-11-20 13:02 UTC, iluwatar commented
Oh yes, that would be great @mohanaraosv Please comment on the issue and I'll assign it for you.