loan pattern 4/10/2022
iluwatar/java-design-patterns pull request #2050
Opened 2022-10-04 09:15 UTC by u7341910

loan pattern issue1843. Could you help check my understanding？

2022-10-08 16:21 UTC, iluwatar requested changes
Hey, thanks for submitting the PR. This is a good start. I added some comments inline to the source code. Additionally, please check these issues

- The build is failing. Please investigate the cause.
- The usual stuff like the readme.md is missing. Check the contribution instructions https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-10-08 16:21 UTC, iluwatar commented on loan-pattern/pom.xml
> +    </properties>
We use Java 11 at the moment. The values come from the parent pom.xml and need not be specified here.

2022-10-08 16:21 UTC, iluwatar commented on loan-pattern/pom.xml
> +
Please add maven-assembly-plugin so that the example can be executed from the command line

2022-10-08 16:21 UTC, iluwatar commented on loan-pattern/src/main/java/com/iluwatar/loan/pattern/App.java
> +public class App {
Here, above the app, please add an explanation of the pattern and how this example implements it

2022-10-08 16:21 UTC, iluwatar commented on loan-pattern/src/main/java/com/iluwatar/loan/pattern/App.java
> +        readFile("loan-pattern/src/main/resources/data.txt");
Add comments what is happening here

2022-10-08 16:21 UTC, iluwatar commented on loan-pattern/src/main/java/com/iluwatar/loan/pattern/Lender.java
> +public class Lender {
Annotate the classes and methods with Javadoc

2022-10-13 12:18 UTC, u7341910 commented
What does “Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project loan-pattern: You have 52 Checkstyle violations” this mean？

2022-10-13 14:06 UTC, u7341910 commented
![图片](https://user-images.githubusercontent.com/111032366/195619290-cb9e1c52-5f5a-4bf9-98d9-d289899663ff.png)

2022-10-13 14:07 UTC, u7341910 commented
> ![图片](https://user-images.githubusercontent.com/111032366/195619290-cb9e1c52-5f5a-4bf9-98d9-d289899663ff.png)
I can't understand this error. Could you help me slove this problem?

2022-10-13 23:22 UTC, u7341910 commented
How could I update the node.js?

2022-10-17 17:14 UTC, iluwatar commented
@u7341910 the sonar error has been fixed in the master branch. You can get it working in your branch too by rebasing your branch on top of master.

2022-10-17 23:43 UTC, u7341910 commented
Still encountered the same problem.

2022-10-20 06:44 UTC, u7341910 commented
Hello, when will the node.js update problem be solved?

2022-10-26 18:21 UTC, iluwatar commented
> Hello, when will the node.js update problem be solved?

It has been resolved in https://github.com/iluwatar/java-design-patterns/pull/2073, but I'm not sure why it's not working here.  However, we can ignore that for now and concentrate on resolving the review comments.

2022-12-01 16:54 UTC, iluwatar requested changes

2022-12-01 16:54 UTC, iluwatar commented on loan-pattern/README.md
> +---
This looks a bit malformed. Please double check that it conforms with https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-12-01 16:54 UTC, iluwatar commented on loan-pattern/etc/data.txt
> +9
Does this file need to be stored in version control or is it generated?

2022-12-01 16:54 UTC, iluwatar commented on loan-pattern/src/main/java/com/iluwatar/loan/pattern/Lender.java
> +public class Lender {
You should describe the Lender class there ^

2023-02-14 20:03 UTC, closed without merging