#1299 Add Identity Map Pattern
iluwatar/java-design-patterns pull request #2094
Opened 2022-10-16 08:37 UTC by u7275858

* Resolves issue #1299 
* The idea of the pattern is as follows:
  * The user looks a record with a particular key.
  * Instead of going to the database to find the record we first look inside a hash table which consists of some recently used records. If key is present here, then just return the record. If not,
  * Look for the key in the database.
* This design pattern essentially works on the principle of caching.

2022-10-22 06:40 UTC, iluwatar requested changes
Looks good in general. I added a few comments here and there. If you can please check these issues then we can proceed with the merge.

2022-10-22 06:40 UTC, iluwatar commented on identity-map/README.md
> +categories: Object-Relational Behavioral
```suggestion
categories: Data access
```

2022-10-22 06:40 UTC, iluwatar commented on identity-map/README.md
> +
Please add explanation section with a programmatic example. See how it's written in the other patterns.

2022-10-22 06:40 UTC, iluwatar commented on identity-map/pom.xml
> +    </properties>
Let's leave these out. The Java version to be used comes from the parent pom.xml.

2022-10-22 06:40 UTC, iluwatar commented on identity-map/pom.xml
> +    </dependencies>
Please add a dependency to maven-assembly-plugin so that we can execute the code example from the command line e.g. `java -jar identity-map.jar`

2022-10-22 06:40 UTC, iluwatar commented on identity-map/src/main/java/com/iluwatar/identitymap/PersonDbSimulatorImplementation.java
> +    throw new IdNotFoundException(ID_STR + personNationalID + NOT_IN_DATA_BASE);
In modern Java, we can do this kind of operations using streams effectively reducing the code size to one-liners

2022-10-22 06:40 UTC, iluwatar commented on identity-map/src/main/java/com/iluwatar/identitymap/PersonFinder.java
> +  }
Use Lombok

2022-10-22 11:33 UTC, u7275858 commented
Hi iluwatar,
I have made the relevant changes as requested.

2022-10-30 16:48 UTC, iluwatar requested changes

2022-10-30 16:48 UTC, iluwatar commented on identity-map/README.md
> +---
Please check the YAML frontmatter requirements in https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute. Basically we can leave out some of these tags.

2022-10-31 00:09 UTC, u7275858 commented
Hi @iluwatar I have made the change.

2022-11-09 19:55 UTC, merged

2022-11-09 19:56 UTC, iluwatar commented
Well done @u7275858 Thank you for contributing this new pattern!

@all-contributors please add @u7275858 for code