Closes #2124 Translate the adapter readme to Spanish
iluwatar/java-design-patterns pull request #2126
Opened 2022-10-19 20:37 UTC by aitorfi

# Translate the adapter readme to Spanish
Translates the adapter design pattern's readme file to Spanish. Closes #2124

2022-10-26 17:45 UTC, iluwatar requested changes

2022-10-26 17:45 UTC, iluwatar commented on localization/es/adapter/README.md
> +---
Please check the new yaml frontmatter requirements at https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-11-05 15:25 UTC, iluwatar approved these changes

2022-11-05 15:25 UTC, merged

2022-11-05 15:26 UTC, iluwatar commented
Thanks @aitorfi, well done!

@all-contributors please add @aitorfi for translation

2022-11-14 14:34 UTC, KarmaTashiCat commented
Hello, if is needed contribution to spanish translation I can do one or more. @iluwatar If it is please tell me from wich file I should start for not make the same as @aitorfi would working. Next pattern readme.md would be aggregator-microservice. I can start with it, or next or 3d or 10th next, the last ... tell me and I will start with one and followings.

2022-11-14 17:50 UTC, aitorfi commented
Hello @KarmaTashiCat, I'm not currently working on any translations so pick the design pattern you want. You could create an issue for each translation and that way everyone will know what you are working on. Also, for future conversations on Spanish translations it would be better to use the issue #2277 instead of an already merged PR.