#2121 - Add hindi localization support for a few patterns
iluwatar/java-design-patterns pull request #2128
Opened 2022-10-20 03:39 UTC by rishu1601

Added the hindi localization for:
- adpater
- factory
- observer
- prototype
- singleton
- strategy

2022-10-20 17:14 UTC, rishu1601 commented
Hey @iluwatar , waiting for your review

2022-10-24 04:52 UTC, rishu1601 commented
Hi @iluwatar , please review this PR

2022-10-27 04:29 UTC, rishu1601 commented
Hi @iluwatar

2022-11-05 08:44 UTC, iluwatar commented
Part of issue #2279

2022-11-05 08:46 UTC, iluwatar requested changes
Additionally, there is a conflict preventing the merge. Please resolve it.

2022-11-05 08:46 UTC, iluwatar commented on localization/hi/adapter/README.md
> +---
Have a look at the updated yaml frontmatter requirements at https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute. You can drop some of the tags. Check this for all the patterns in this PR.

2023-01-19 11:51 UTC, closed without merging