#393 Added notification pattern
iluwatar/java-design-patterns pull request #2133
Opened 2022-10-21 11:23 UTC by DateNolan

Added the notification design pattern along with tests and readme. However unfortunately had some issues with getting the uml diagram to auto generate, would appreciate some help with that.

I would also like to mention that this code is similar but seperate to NatalieSty's implementation of the same pattern, we both adapted our code from the same source and as such I would like to acknowledge their contribution to this pattern.

2022-10-21 16:56 UTC, vishhhhhhhh commented
Looks good :)

2022-10-29 06:55 UTC, iluwatar requested changes

2022-10-29 06:55 UTC, iluwatar commented on notification/README.md
> +---
Please check the updated yaml frontmatter requirements in https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute.

To the tags we could also add `Domain`

2022-10-29 06:55 UTC, iluwatar commented on notification/README.md
> +17:19:17.909 [main] INFO com.iluwater.notification.RegisterWorkerForm - Not registered, see errors
Should be com.iluwatar, please check the package naming

2022-10-29 06:55 UTC, iluwatar commented on notification/pom.xml
> +        </dependency>
Use the version from the parent pom.xml

2022-10-29 06:55 UTC, iluwatar commented on notification/pom.xml
> +            </plugin>
This plugin is already present in the parent pom.xml, so no need to add it here

2022-10-29 06:55 UTC, iluwatar commented on notification/src/main/java/com/iluwater/notification/App.java
> + */
In this section, please explain the pattern idea briefly and then describe how the example code implements it

2022-10-29 06:55 UTC, iluwatar commented on notification/src/main/java/com/iluwater/notification/App.java
> +    RegisterWorkerForm form = new RegisterWorkerForm(NAME, OCCUPATION, DATE_OF_BIRTH);
You can use `var` keyword for local variables

2022-10-29 07:39 UTC, DateNolan commented
@iluwatar Resolved all feedback given!

2022-11-06 12:28 UTC, iluwatar commented on notification/pom.xml
> +        </dependency>
the version could be left out completely to use the one from the parent, but it's not a big deal

2022-11-06 12:34 UTC, iluwatar commented on notification/pom.xml
> +        </dependency>
Oh, actually it is and causes a build error. 

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.projectlombok:lombok:jar must be a valid version but is '${lombok.version}'. @ line 28, column 22
```

2022-11-06 12:34 UTC, iluwatar commented on notification/pom.xml
> +        </dependency>
Please resolve this issue and we can proceed with the merge @DateNolan

2022-11-06 22:46 UTC, DateNolan commented
@iluwatar  I believe I resolved the issue with versioning

2022-11-23 18:56 UTC, iluwatar requested changes

2022-11-23 18:56 UTC, iluwatar commented on notification/README.md
> +---
The frontmatter needs still adjustments. If you look at the requirements at https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute, you'll notice that there is no `layout` and `tags` should be renamed to `tag`.

2022-11-23 18:56 UTC, iluwatar commented on notification/src/main/java/com/iluwater/RegisterWorkerDto.java
> +  }
Perhaps these params could be set in the constructor?

2022-11-23 18:56 UTC, iluwatar commented on notification/src/test/java/com/iluwater/DateOfBirthErrorTest.java
> +    LocalDate dateOfBirth = LocalDate.of(2016, 7, 13);
Use `var` for local variables

2022-11-23 18:56 UTC, iluwatar commented on notification/src/test/java/com/iluwater/DateOfBirthErrorTest.java
> +    LocalDate dateOfBirth = LocalDate.of(2016, 7, 13);
Check this elsewhere too

2022-11-23 18:56 UTC, iluwatar commented on notification/src/main/java/com/iluwater/RegisterWorkerForm.java
> +  RegisterWorkerService service = new RegisterWorkerService();
Is this constructor used anywhere?

2022-11-23 18:56 UTC, iluwatar commented on notification/src/main/java/com/iluwater/RegisterWorkerForm.java
> +  }
You can use Lombok to create this kind of constructors

2023-02-08 00:01 UTC, closed without merging

2023-02-18 18:52 UTC, iluwatar commented
https://github.com/iluwatar/java-design-patterns/issues/393