Dependent Mapping pattern #1293
iluwatar/java-design-patterns pull request #2197
Opened 2022-10-28 17:31 UTC by Adrianp3623

Pull request title

- Clearly and concisely describes what it does
- Refer to the issue that it solves, if available

Pull request description

Dependent Mapping pattern [#1293](https://github.com/iluwatar/java-design-patterns/issues/1293) may have been done.
Please review this pull request.

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-10-30 16:50 UTC, Adrianp3623 commented
@iluwatar please review this pull request. This pull request resolve [Dependent Mapping pattern #1293](https://github.com/iluwatar/java-design-patterns/issues/1293).

2022-11-08 18:44 UTC, iluwatar requested changes

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/README.md
> +---
Study https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute to see how the yaml frontmatter should be implemented

I recommend using category `Structural` and tags `Data access`. See https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/README.md
> +perform track mapping and treat this mapping as a related mapping.
Use a bullet list

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/pom.xml
> +    </properties>
Use the version from the parent pom.xml

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/pom.xml
> +        </dependency>
Let's use JUnit

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/pom.xml
> +        </dependency>
Hmm, why do you need this?

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/main/java/com/iluwatar/dependentmapping/Album.java
> +  }
Use Lombok where possible

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/main/java/com/iluwatar/dependentmapping/AlbumMapper.java
> +    String title = rs.getString(parameterIndex2);
Prefer `var` keyword for local variables

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/main/java/com/iluwatar/dependentmapping/AlbumMapper.java
> +      System.out.println("--update master object work done--");
Use a proper logger

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/main/java/com/iluwatar/dependentmapping/App.java
> + * as a related mapping.
You could start with the pattern name e.g. In the dependent mapping pattern...

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/main/java/com/iluwatar/dependentmapping/App.java
> +    statement.execute("truncate table tracks");
Could move these to a separate method

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/main/java/com/iluwatar/dependentmapping/App.java
> +    displayTracks(resultSet);
Add comments to describe what is happening

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/test/java/com/iluwatar/dependentmapping/AlbumMapperTest.java
> +  void findstatement() throws SQLException {
Consider better naming for the test methods

2022-11-08 18:44 UTC, iluwatar commented on dependent-mapping/src/test/java/com/iluwatar/dependentmapping/AlbumMapperTest.java
> +    connectDB();
You could connect in before-test handler or even before-class

2023-01-22 23:04 UTC, closed without merging