#1842 Add Currying Design Pattern
iluwatar/java-design-patterns pull request #2271
Opened 2022-10-29 22:21 UTC by hkattt

This PR resolves #1842.

I adapted the currying example suggested in the #1842 thread. My programmatic example focuses on using a curried builder function to create Book objects.

2022-11-07 21:23 UTC, hkattt commented
Hey @iluwatar, apologies for that. I plan on continuing work on this issue in about 2 weeks time. Sorry for the delay.

2022-11-27 13:50 UTC, iluwatar requested changes
We need a couple of minor changes. Otherwise, this looks very good!

2022-11-27 13:50 UTC, iluwatar commented on currying/README.md
> +---
Please implement the yaml frontmatter according to https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-11-27 13:50 UTC, iluwatar commented on currying/src/main/java/com/iluwatar/currying/Book.java
> +  }
Use Lombok to reduce boilerplate

2022-11-27 13:50 UTC, iluwatar commented on currying/src/main/java/com/iluwatar/currying/Genre.java
> +  }
Doesn't look useful

2022-11-28 01:27 UTC, hkattt commented
Hey @iluwatar, I made the changes that you requested; however, the build fails when executing the Maven goal for the service-layer design pattern. Do you have any idea what might be causing this issue?

2022-12-03 17:05 UTC, iluwatar commented
Perhaps try to rebase your branch on top of `master` to get rid of the build errors?

2022-12-04 03:28 UTC, hkattt commented
Hey @iluwatar, made the changes that you asked for and the tests are now passing.

2022-12-04 09:48 UTC, iluwatar approved these changes

2022-12-04 09:48 UTC, merged

2022-12-04 09:50 UTC, iluwatar commented
Excellent, thank you for contributing the new design pattern! 🎉😄💪

@all-contributors please add @hkattt for code

2022-12-04 09:52 UTC, iluwatar commented
@all-contributors please add @hkattt for code