Translate:  Translate the aggregator-microservices readme to Spanish [Issue #2335 (Task of issue #2277 )]
iluwatar/java-design-patterns pull request #2338
Opened 2022-11-16 12:01 UTC by KarmaTashiCat

Translated [aggregator-microservices/README.md](https://github.com/iluwatar/java-design-patterns/blob/master/aggregator-microservices/README.md) and saved translation to [/localization/es/](https://github.com/iluwatar/java-design-patterns/tree/master/localization/es) ./aggregator-microservices/README.md

2022-11-16 12:09 UTC, KarmaTashiCat commented
Translate the aggregator-microservices readme to Spanish [Issue #2335 (Task of issue #2277 )]

2022-11-27 13:52 UTC, iluwatar requested changes

2022-11-27 13:52 UTC, iluwatar commented on localization/es/aggregator-microservices/README.md
> +---
The yaml frontmatter keys are not supposed to be translated, only values.

2022-11-27 17:53 UTC, KarmaTashiCat reviewed
I'm sorry , It's my first issue and pull request, and as mistake I've submitted before changes, but now I've made the changes hoping everything is ok according the recent commits from issue #2353 but I'm confused about the tag keyword because I was trying to figure out about YAML keys and reading some documentation saying that "tags" is the right keyword but now is switched for "tag" keyword. Sorry for my confusion, trying to figure it out the changes requested, I've forked and commited pullrequest before #2353 newest commits, I hope that now "tag" was expected in changes requested too instead old version "tags" keyword.
I will still paying attention to news about this question and if could it be merged or not yet, thank you for changes request @iluwatar I will try to considere it in future PRs.

2022-12-03 16:44 UTC, iluwatar requested changes
The current convention is to keep the yaml frontmatter untranslated, so let's stick to that. Otherwise, looks good.

2022-12-03 16:44 UTC, iluwatar commented on localization/es/aggregator-microservices/README.md
> +title: Aggregator Microservices (Agregador de microservicios)
```suggestion
title: Aggregator Microservices
```

2022-12-03 16:44 UTC, iluwatar commented on localization/es/aggregator-microservices/README.md
> +category: Architectural (Arquitectónico)
```suggestion
category: Architectural
```

2022-12-03 16:44 UTC, iluwatar commented on localization/es/aggregator-microservices/README.md
> +- Cloud distributed (Nube distribuida)
```suggestion
- Cloud distributed
```

2022-12-03 16:44 UTC, iluwatar commented on localization/es/aggregator-microservices/README.md
> +- Decoupling (Desacoplamiento)
```suggestion
- Decoupling
```

2022-12-03 16:44 UTC, iluwatar commented on localization/es/aggregator-microservices/README.md
> +- Microservices (Microservicios)
```suggestion
- Microservices
```

2022-12-14 13:19 UTC, KarmaTashiCat commented
> The current convention is to keep the yaml frontmatter untranslated, so let's stick to that. Otherwise, looks good.

Resolved! Ty for RC!

2022-12-28 18:09 UTC, iluwatar commented
@KarmaTashiCat please rebase the branch on top of master. This should resolve the sonar analysis error.

2022-12-29 18:53 UTC, iluwatar approved these changes

2022-12-29 18:53 UTC, merged

2022-12-29 18:54 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @KarmaTashiCat for translation