Added detailed explanation of type object pattern
iluwatar/java-design-patterns pull request #2344
Opened 2022-11-19 14:34 UTC by PraveenNanda124

## #type object pattern explanation

- the type object pattern explanation added
- #2266 

Pull request description

- Describes the explanation includes real time example and programmatic example

2022-11-19 14:55 UTC, PraveenNanda124 reviewed
Wikipedia saying not available

2022-11-23 15:57 UTC, PraveenNanda124 commented
@iluwatar is this enough or should I add something

2022-12-01 16:34 UTC, iluwatar requested changes

2022-12-01 16:34 UTC, iluwatar commented on typeobjectpattern/README.md
> +};
I'm sorry, but this doesn't look like Java. Please reference the code in this repository.

2023-02-14 20:03 UTC, closed without merging