translation of facade design pattern to PT-BR
iluwatar/java-design-patterns pull request #2355
Opened 2022-11-20 20:03 UTC by Viniberaldo

translation of facade design pattern to PT-BR

2022-11-23 16:03 UTC, PraveenNanda124 reviewed
Good work

2022-12-01 16:35 UTC, iluwatar requested changes

2023-01-15 08:35 UTC, iluwatar approved these changes

2023-01-15 08:35 UTC, merged

2023-01-15 08:36 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @Viniberaldo for translation

2023-01-15 08:37 UTC, iluwatar commented
Part of issue https://github.com/iluwatar/java-design-patterns/issues/2285