fix:added code refactoring changes for 2378
iluwatar/java-design-patterns pull request #2379
Opened 2022-12-02 14:13 UTC by Ap284

Pull request title

- Clearly and concisely describes what it does
- Refer to the issue that it solves, if available

Pull request description

- Describes the main changes that come with the pull request
- Any relevant additional information is provided

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2022-12-04 09:19 UTC, iluwatar requested changes

2022-12-04 09:19 UTC, iluwatar commented on collection-pipeline/pom.xml
> +        </plugin>
This is now set in the parent pom.xml. Please rebase your changes on top of `master`. Let's see if we get a passing build.

2022-12-05 20:16 UTC, iluwatar commented on collection-pipeline/pom.xml
> +        </plugin>
You have the same configuration elsewhere too. Please check throughout the code.

2022-12-05 20:17 UTC, iluwatar commented
Please try to address the failing build

2022-12-05 20:19 UTC, iluwatar requested changes
The build needs to pass before we can merge

2022-12-09 11:36 UTC, Ap284 commented
Hi @iluwatar,
I have rebased changes with master still getting same issue:

Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project java-design-patterns: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator -> [Help 1]

2022-12-09 13:44 UTC, Ap284 commented
Hi @iluwatar,

I have sync the fork with the upstream master branch. But, still getting the same issue:

Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project java-design-patterns: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator -> [Help 1]

Please, guide me if I missed anything or anything incorrect.

2022-12-10 14:54 UTC, iluwatar commented
The build works for me locally, so I don't think there's anything wrong in this branch. I recently reconfigured the Sonar scan, but maybe it's using the old one from the cache or something like that. Anyway, I'm going to merge this.

2022-12-10 14:54 UTC, iluwatar approved these changes

2022-12-10 14:55 UTC, merged

2022-12-10 14:56 UTC, iluwatar commented
@all-contributors please add @Ap284 for code