Translate Abstract Factory to Russian / Fix #2286 partially
iluwatar/java-design-patterns pull request #2533
Opened 2023-06-04 11:22 UTC by VladimirCreator

This pull request localizes the description of the abstract factory design pattern to Russian.

2023-06-04 11:22 UTC, VladimirCreator commented
You can assign the issue #2286 to me.

2023-07-02 07:35 UTC, iluwatar requested changes

2023-07-02 07:35 UTC, iluwatar commented on localization/ru/abstract-factory/README.md
> +category: Creationsl
should be Creational

2023-07-02 07:36 UTC, iluwatar commented
> You can assign the issue #2286 to me.

Please comment on the issue, otherwise I am not able to assign it to you

2023-08-20 07:35 UTC, iluwatar approved these changes

2023-08-20 07:35 UTC, merged

2023-08-20 07:36 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @VladimirCreator for translation