[Scheduler Pattern] (Add) scheduler pattern #76
iluwatar/java-design-patterns pull request #2584
Opened 2023-09-10 09:03 UTC by tiennm99

I just implemented common and easy to understand disciplines like: First Come First Served, Priority scheduling, Shortest remaining time first, Round-robin scheduling.

It would be great if someone were generous enough to implement more complicated disciplines.

2023-10-08 08:49 UTC, iluwatar requested changes

2023-10-08 08:49 UTC, iluwatar commented on scheduler/README.md
> +tag:
Please pick suitable tags from https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags

2023-10-08 08:49 UTC, iluwatar commented on scheduler/README.md
> +The Scheduler Design Pattern is designed to decouple task scheduling from the actual execution of tasks. It abstracts the scheduling logic, making it possible to change or extend the scheduling behav
The explanation section consists of multiple subsections. See https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template

2023-10-08 08:49 UTC, iluwatar commented on scheduler/pom.xml
> +    </properties>
No need to set these here, they come from the parent pom.xml

2023-10-08 08:49 UTC, iluwatar commented on scheduler/pom.xml
> +            <version>5.9.2</version>
The version property can be left out and use the latest

2023-10-08 08:49 UTC, iluwatar commented on scheduler/src/test/java/com/iluwatar/scheduler/FirstComeFirstServedSchedulerTest.java
> +}
Best practise is to create App.java with main function to run the example (see the other patterns). I think we can move this class under tests then.

2023-10-08 13:04 UTC, tiennm99 commented
Gotcha, I'll fix them later. Maybe on next weekend.

2023-10-16 13:48 UTC, tiennm99 commented
I fixed problems in your comments. Please check them again @iluwatar

2023-10-26 18:46 UTC, iluwatar commented
Please check the failing build and conflicts

2024-01-09 19:41 UTC, closed without merging

2024-01-10 10:45 UTC, tiennm99 commented
Sorry I'm too busy these days. I will fix it by the end of Jan 2024.

2024-01-20 03:18 UTC, tiennm99 commented
I have created new PR #2794