Updated CI
iluwatar/java-design-patterns pull request #2640
Opened 2023-10-12 14:00 UTC by ohbus

Removed duplicate maven caching and removed full namespace for the sonar plugin

Also updated the JDK to corretto

2023-10-12 14:12 UTC, ohbus commented
@iluwatar I want to rejoin as a collaborator and help maintain this project and the other ones.

2023-10-22 17:46 UTC, iluwatar requested changes

2023-10-22 17:46 UTC, iluwatar commented on .github/workflows/maven-ci.yml
> +        distribution: 'corretto'
Hmm, why should we switch from temurin?

2023-10-22 17:46 UTC, iluwatar commented on .github/workflows/maven-ci.yml
> -
This seems to remove the local maven repository caching?

2023-10-22 17:46 UTC, iluwatar commented on .github/workflows/maven-pr-builder.yml
> +        -Dsonar.pullrequest.key=$PR_NUMBER
Yeah, this looks prettier (if it works)

2023-10-22 17:46 UTC, iluwatar commented
> @iluwatar I want to rejoin as a collaborator and help maintain this project and the other ones.

Noted, let me consider

2024-01-05 22:38 UTC, closed without merging