Update README.md
iluwatar/java-design-patterns pull request #2652
Opened 2023-10-14 12:55 UTC by pushpander1010

Added explanation, programming example | Explanation for Half-Sync/Half-Async

Added a programmatic example and easy to understand explanation for Half-Sync/Half-Async design pattern.

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2023-10-24 17:43 UTC, pushpander1010 commented
Please merge it

2023-12-27 06:23 UTC, iluwatar requested changes
Well written, but the explanation seems to be disconnected from the code example. I think that the explanation should be based on the actual code we have. Could you update accordingly?

2024-03-17 07:39 UTC, iluwatar approved these changes

2024-03-17 07:40 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @pushpander1010 for docs

2024-03-27 14:48 UTC, merged