Issue1843 loan pattern
iluwatar/java-design-patterns pull request #2708
Opened 2023-10-17 23:30 UTC by Shelly-Shih

Loan Design Pattern

- Add the example of loan design pattern
- Issue: https://github.com/iluwatar/java-design-patterns/issues/1843

Pull request description

- Add a new loan design pattern

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2023-10-18 00:42 UTC, Shelly-Shih commented
To maintainer, 
I just created a pull request. Please let me know what you think.
Many Thanks.

2023-10-28 07:38 UTC, iluwatar requested changes

2023-10-28 07:38 UTC, iluwatar commented on loan/README.md
> +- Financial Management
Let's try to stick with the existing tags, if possible. See https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags

2023-10-28 07:38 UTC, iluwatar commented on loan/README.md
> +
Please add "Explanation" section according to https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template

2023-10-28 07:38 UTC, iluwatar commented on loan/README.md
> +## Real world examples
Remove the empty heading

2023-10-28 07:38 UTC, iluwatar commented on loan/README.md
> +![alt text](./etc/loan.png "Loan Pattern Diagram")
Prefer to use urm-maven-plugin to generate the diagram

2023-10-28 07:38 UTC, iluwatar commented on loan/src/main/java/com/iluwatar/loan/Main.java
> +
Here, above the main class (usually named App.java), please explain the pattern briefly. Describe how the code example implements the pattern.

2023-10-28 07:38 UTC, iluwatar commented on loan/src/test/java/com/iluwatar/loan/MainTest.java
> +public class MainTest {
We usually have AppTest that runs the example and checks there are no errors. Then we have a set of unit tests.

2023-10-28 07:38 UTC, iluwatar commented on loan/src/test/java/com/iluwatar/loan/MainTest.java
> +        System.out.println("Current working directory: " + currentDirectory);
Prefer to use a proper logger (from Lombok, for example)

2024-01-11 14:03 UTC, closed without merging