feat(microservices-self-registration): completed discovery server and…
iluwatar/java-design-patterns pull request #2779
Opened 2023-11-28 17:28 UTC by Pat-r1ck

Microservices Self Registration #2687 

- Microservice structure contains discovery-server & client service
- During startup, client service would register itself with the discovery-server
- During crash, client service would unregister itself from the discovery-server

2024-01-29 06:53 UTC, Pat-r1ck commented
@iluwatar please review my pull request, thank you

2024-03-10 09:51 UTC, iluwatar requested changes
Additionally, please add this module to the parent `pom.xml`. Otherwise it's not built by CI.

2024-03-10 09:51 UTC, iluwatar commented on microservices-self-registration/client-service/pom.xml
> +    </properties>
Not needed, these come from parent `pom.xml`

2024-03-10 09:51 UTC, iluwatar commented on microservices-self-registration/client-service/src/main/java/com/patrick/clientservice/ClientServiceApplication.java
> +public class ClientServiceApplication
Add JavaDoc to explaing the purpose of this class and its role in the pattern

2024-03-10 09:51 UTC, iluwatar commented on microservices-self-registration/discovery-server/pom.xml
> +    </properties>
not needed

2024-03-10 09:51 UTC, iluwatar commented on microservices-self-registration/discovery-server/src/main/java/com/patrick/discoveryserver/DiscoveryServerApplication.java
> +public class DiscoveryServerApplication
Add JavaDoc to explaing the purpose of this class and its role in the pattern

2024-07-06 18:57 UTC, closed without merging