Service-Oriented Architecture pattern (#2937)
iluwatar/java-design-patterns pull request #2946
Opened 2024-05-07 12:50 UTC by romannimets

## What problem does this PR solve?

Related issue: [Service-Oriented Architecture pattern (#2937)](https://github.com/iluwatar/java-design-patterns/issues/2937)
Introduces the Service-Oriented Architecture (SOA) pattern to enhance modular service interaction.

This PR addresses the need to implement Service-Oriented Architecture (SOA) to improve the interaction between modular services within the application. The SOA pattern facilitates loose coupling, service abstraction, reusability, interoperability, scalability, statelessness, discoverability, and security, enhancing the overall architecture of the system.

The main points considered when implementing SOA are:

- **Loose Coupling:** Services should operate independently without knowledge of other services.
- **Service Abstraction:** Services hide complexity behind a clear interface.
- **Service Reusability:** Services are designed for reuse across different parts of the application.
- **Interoperability:** Services operate with other services using standard protocols.
- **Scalability:** Services can be scaled independently to handle increasing loads.
- **Statelessness:** Services handle each request independently, increasing reliability.
- **Discoverability:** Services can be easily discovered through standard mechanisms.
- **Security:** Robust security measures are implemented to secure communication and data access.

Implementing SOA involves setting up a service registry, defining service interfaces, ensuring security protocols, and creating middleware for efficient service communication. Each service functions as a discrete unit of functionality, facilitating a flexible and adaptable software environment.

2024-06-21 05:12 UTC, ylcn91 requested changes

2024-06-21 05:12 UTC, ylcn91 commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/services/classes/PersonalizedGreetingServiceImpl.java
> +    switch (currentWeather) {
Switch expressions can make this cleaner 

Something like that: 

return switch (currentWeather) {
            case SUNNY -> "What a good sunny day";  
            case RAINY -> "What a rainy day"; 
            ...
            ...
            default -> "Hello, and hope you have a great day despite the weather"; 
        };

2024-06-21 05:12 UTC, ylcn91 commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/controller/LoginController.java
all class as comment?

2024-06-21 05:12 UTC, ylcn91 commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/security/WebSecurityConfig.java
> +        .logout(LogoutConfigurer::permitAll);
LogoutConfigurer::permitAll  -- > ensure that only the logged-in user can initiate their own logout

2024-06-21 05:12 UTC, ylcn91 commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/controller/GreetingController.java
> +public class GreetingController {
Maybe we can consider a @ControllerAdvice to handle errors in controllers? or we can handle it try / catch if something goes wrong?

2024-06-22 14:47 UTC, romannimets commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/services/classes/PersonalizedGreetingServiceImpl.java
> +  private final GreetingService greetingService;
perferct, thanks for the insight

2024-06-22 15:00 UTC, romannimets commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/SOAExampleApplication.java
> +  private static final Logger log = LoggerFactory.getLogger(SOAExampleApplication.class);
i did it with Slf4j because i wanted a static logger to use in my main class, if it doesnt seem right let me know!

2024-06-22 15:28 UTC, romannimets commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/SOAExampleApplication.java
> +  private static void configureAndRegisterServices() {
done, let me know if it looks good enough

2024-06-22 15:32 UTC, romannimets commented on service-oriented-architecture/src/main/java/com/iluwatar/soa/services/registry/ServiceRegistry.java
> +  public static void registerService(String serviceName, Object serviceInstance) {
thanks a lot! Did this, hope it looks good enough

2024-09-06 06:08 UTC, closed without merging