Feature/fuction composition
iluwatar/java-design-patterns pull request #2954
Opened 2024-05-14 14:20 UTC by Adelechka

Function Composition pattern (https://github.com/iluwatar/java-design-patterns/issues/2897)

Related: https://github.com/iluwatar/java-design-patterns/issues/2897
Pull request description

sample java code with javadoc
test code
UML diagram
README.md file

2024-05-14 15:18 UTC, iluwatar requested changes
The changes seem to contain also Virtual Proxy. Please isolate them from this PR - this should be only about Function Composition.

2024-05-14 17:33 UTC, Adelechka commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/5333b8e2ff49bd5efdc6d2efd30ec08d7ac8d67c5e80190d03b6c2cb29a5de8b/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=iluwatar_java-design-patterns&pullRequest=2954) **Quality Gate failed**
> Failed conditions ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=iluwatar_java-design-patterns&pullRequest=2954&resolved=false&sinceLeakPeriod=true) ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [75.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=iluwatar_java-design-patterns&pullRequest=2954&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=iluwatar_java-design-patterns&pullRequest=2954)

problems found in a file that is not in my pull request

2024-05-15 05:58 UTC, iluwatar requested changes

2024-05-15 05:58 UTC, iluwatar commented on function-composition/README.md
> +title: Function Composer
```suggestion
title: Function Composition
```

2024-05-15 05:58 UTC, iluwatar commented on function-composition/README.md
> +## Name / classification
this section not needed, see https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template

2024-05-15 05:58 UTC, iluwatar commented on function-composition/README.md
> +  - Java
Prefer tags from the list https://github.com/iluwatar/java-design-patterns/wiki/07.-Categories-and-Tags

2024-05-15 05:58 UTC, iluwatar commented on function-composition/pom.xml
> +        </dependency>
not needed, comes from the parent

2024-06-01 02:26 UTC, iluwatar approved these changes

2024-06-01 02:26 UTC, merged

2024-06-01 02:27 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @Adelechka for code