Feature/virtual proxy
iluwatar/java-design-patterns pull request #2955
Opened 2024-05-14 16:34 UTC by Adelechka

Virtual Proxy Pattern (https://github.com/iluwatar/java-design-patterns/issues/2940)

Related: https://github.com/iluwatar/java-design-patterns/issues/2940
Pull request description

sample java code with javadoc
test code
UML diagram
README.md file

2024-05-14 17:28 UTC, Adelechka commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/5333b8e2ff49bd5efdc6d2efd30ec08d7ac8d67c5e80190d03b6c2cb29a5de8b/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=iluwatar_java-design-patterns&pullRequest=2955) **Quality Gate failed**
> Failed conditions ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=iluwatar_java-design-patterns&pullRequest=2955&resolved=false&sinceLeakPeriod=true)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=iluwatar_java-design-patterns&pullRequest=2955)

file with 1 Security Hotspot isn't in my pull request

2024-05-15 05:53 UTC, iluwatar requested changes

2024-05-15 05:53 UTC, iluwatar commented on proxy/pom.xml
> +                  <mainClass>com.iluwatar.com.App</mainClass>
This change is not intended?

2024-05-15 06:53 UTC, iluwatar approved these changes

2024-05-15 06:53 UTC, merged

2024-05-15 06:54 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @Adelechka for code