Active Record Pattern #79
iluwatar/java-design-patterns pull request #3087
Opened 2024-11-05 19:28 UTC by ipaulaandreea

Adds active record pattern

Close https://github.com/iluwatar/java-design-patterns/issues/79

2024-11-10 08:53 UTC, iluwatar requested changes

2024-11-10 08:53 UTC, iluwatar commented on active-record/database.db
Is this file necessary, or is created on demand?

2024-11-10 08:53 UTC, iluwatar commented on active-record/pom.xml
> +            <version>1.18.30</version> <!-- Added -->
We should use the version from the parent

2024-11-10 08:53 UTC, iluwatar commented on active-record/pom.xml
> +        </dependency>
Using H2 database is highly recommended (see https://github.com/iluwatar/java-design-patterns/wiki/10.-Technology-selections)

2024-11-10 08:53 UTC, iluwatar commented on active-record/src/main/java/com/iluwatar/activerecord/User.java
> +  public static User findById(int id) throws SQLException {
Perhaps return `Optional<User>`?

2024-11-10 08:53 UTC, iluwatar commented on update-header.sh
> +
Not sure if this script is necessary?

2024-11-15 05:26 UTC, ipaulaandreea commented
Thanks for the cr! Will look into it

2025-01-06 17:48 UTC, closed without merging