Fixed busy waiting in points 1,2,3,7
iluwatar/java-design-patterns pull request #3101
Opened 2024-11-30 05:51 UTC by alhusseain

Close issue #2977
Implemented wait and notify functionalities on threads that have busy waiting issues

No. 1 : Server Session / App.java

sessionExpirationTask now waits until at least a single login request is sent, since unnecessary overhead if it runs with no login requests available.

No. 2 : Twin / BallThread.java

run() now waits if suspendMe is called, and resumes if resumeMe is called, since unnecessary overhead if run() is running when suspended. ( no need to always check if suspended)

No. 3: Log Aggregation / LogAggregator.java
startBufferFlusher no runs if there is at least one log is present, similiar to No.1's fix

No. 7: Queue-Based Load Leveling / ServiceExecutor.java

similiar to No.3 and No.1, at least a single msg is added to queue to work, until then run() waits.

I did not refactor No. 4,5,6 since I think no unnecessary overhead is present ( as the retry pattern implemented loops until certain number of errors occur, doesn't loop needlessly)

I am waiting for feedback, which I would consider and act upon quickly.

2024-12-07 19:26 UTC, alhusseain commented
Quality Gate Gives a Reliability Rate D to a file I did not Change or commit (CandyGame.java) . Also I did not change any thing in LogoutHandlerTest.java So I do not know where the conflict is.

2025-01-11 17:10 UTC, iluwatar requested changes

2025-01-11 17:10 UTC, iluwatar commented on twin/src/main/java/com/iluwatar/twin/BallThread.java
> +          Thread.sleep(250);
This `Thread.sleep(250)` is the main problem. Instead of using a thread, we could utilize the same aforementioned `ScheduledExecutorService `

2025-02-15 20:54 UTC, alhusseain commented on twin/src/main/java/com/iluwatar/twin/BallThread.java
> +          Thread.sleep(250);
On it, Thanks for the feedback

2025-02-18 17:45 UTC, alhusseain commented on twin/src/main/java/com/iluwatar/twin/BallThread.java
> +          Thread.sleep(250);
I have implemented all requested changes except only in BallThread.java. in BallThread.java, There is no need to run it every fixed amount of time. Instead, waking the thread up only when there is a request to resume and making it wait when there is a request to suspend is sufficient to reduce overhead. This way, I implement event-based logic.

2025-02-22 18:03 UTC, iluwatar commented
I'm sorry, but it doesn't look correct. The solution needs a complete rewrite, so I'll close this.

2025-02-22 18:03 UTC, closed without merging