Resolved issue #1323 Two-Step View pattern
iluwatar/java-design-patterns pull request #3106
Opened 2024-12-03 22:19 UTC by sharara6

## What problem does this PR solve?

It creates a two-step view design pattern for more details check the read me file

2024-12-08 21:54 UTC, sharara6 commented
@iluwatar  may you review this PR ?

2024-12-20 21:33 UTC, sharara6 commented
Dear @iluwatar may you check my PR?

2024-12-25 21:59 UTC, sharara6 commented
This is a gentle follow up.

2025-01-11 17:24 UTC, iluwatar requested changes

2025-01-11 17:24 UTC, iluwatar commented on two-step-view/README.md
> +# Book Data Processing and Presentation
`README.md` has a very specific format that needs to be implemented by all the pattern examples. See here: https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

2025-01-11 17:24 UTC, iluwatar commented on two-step-view/pom.xml
> +    </properties>
Comes already from parent pom.xml

2025-01-11 17:24 UTC, iluwatar commented on two-step-view/pom.xml
> +    </dependencies>
Add maven-assembly-plugin to allow executing the jar from the command line. See the other patterns for examples.

2025-01-11 17:24 UTC, iluwatar commented on two-step-view/src/main/java/com/iluwatar/App.java
> +/** Main class. */
Here, above the `App` class, explain the pattern and describe how this example implements it.

2025-01-11 17:24 UTC, iluwatar commented on two-step-view/src/main/java/com/iluwatar/App.java
> +    String htmlOutput = Presentation.presentBook(preparedData);
Add comment

2025-01-11 20:14 UTC, sharara6 commented
Thank you for your review. I am in the midst of final exams right now. May I work on it next week?

2025-01-12 17:16 UTC, iluwatar commented
> Thank you for your review. I am in the midst of final exams right now. May I work on it next week?

Sure, no problem. Good luck with the exams 😄

2025-02-15 07:11 UTC, iluwatar requested changes
Additionally, please resolve the conflicts.

2025-02-15 07:11 UTC, iluwatar commented on two-step-view/README.md
> +# Two-Step View
Add front-matter as instructed in https://github.com/iluwatar/java-design-patterns/wiki/21.-New-Pattern-Template

2025-02-15 07:11 UTC, iluwatar commented on two-step-view/README.md
> +
Add short programmatic example here. See the other patterns for examples of how to do this.

2025-03-18 07:49 UTC, iluwatar commented
Closed due to inactivity. Thank you for the contribution.

2025-03-18 07:49 UTC, closed without merging