Implemented the Template View pattern (#1320)
iluwatar/java-design-patterns pull request #3110
Opened 2024-12-04 23:57 UTC by malak-elbanna

Issue #1320 

I've implemented the Template View pattern according to the criteria and resources given in the issue description. More details about the pattern and the specifics of the implementation can be found in the README file attached with this PR.

2024-12-09 17:09 UTC, iluwatar requested changes
Additionally, please use Java package name `com.iluwatar`

2024-12-09 17:09 UTC, iluwatar commented on templateview/README.md
> +- **Decorator Pattern:** Can complement Template View for dynamically adding responsibilities to views.
Add links to patterns

2024-12-10 19:08 UTC, malak-elbanna commented
Hi @iluwatar, thank you for your comments. I've addressed them!

2025-01-06 17:23 UTC, iluwatar submitted a review, later dismissed

2025-01-06 17:24 UTC, merged

2025-01-06 17:24 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @malak-elbanna for code