Implemented Coarse-Grained pattern issue #1289
iluwatar/java-design-patterns pull request #3124
Opened 2024-12-07 15:04 UTC by unminnn

What problem does this PR solve?

Close #1289 

This PR implements the Coarse-Grained Lock pattern to lock multiple objects instead of a separate lock for each one, and includes an example of a customer and multiple addresses.

2024-12-08 05:42 UTC, unminnn commented
More comprehensive test cases are being worked on currently.

2025-01-06 08:54 UTC, iluwatar requested changes

2025-01-06 08:54 UTC, iluwatar commented on coarse-grained-lock/README.md
> +---
Please follow the frontmatter format exactly. Here is an example from another pattern:

```
---
title: "Abstract Document Pattern in Java: Simplifying Data Handling with Flexibility"
shortTitle: Abstract Document
description: "Explore the Abstract Document design pattern in Java. Learn its intent, explanation, applicability, benefits, and see real-world examples to implement flexible and dynamic data structures."
category: Structural
language: en
tag:
  - Abstraction
  - Decoupling
  - Dynamic typing
  - Encapsulation
  - Extensibility
  - Polymorphism
---

```

2025-01-06 08:54 UTC, iluwatar commented on coarse-grained-lock/pom.xml
> +    </properties>
Not needed, comes from parent pom.xml

2025-01-06 08:54 UTC, iluwatar commented on coarse-grained-lock/pom.xml
> +        </dependency>
Why we need this? Could we stick to JUnit instead?

2025-01-06 08:54 UTC, iluwatar commented on coarse-grained-lock/src/main/java/com/iluwatar/coarse/grained/Address.java
> +}
Use Lombok to get rid of boilerplate like getters and setters

2025-01-06 08:54 UTC, iluwatar commented on coarse-grained-lock/src/main/java/com/iluwatar/coarse/grained/App.java
> +   */
Please explain the pattern briefly and describe how this example implements it

2025-01-06 08:54 UTC, iluwatar commented on coarse-grained-lock/src/main/java/com/iluwatar/coarse/grained/App.java
> +    });
Add comments to the code. Remember this is learning material.

2025-01-06 08:55 UTC, iluwatar commented
Additionally, this module should be added to parent pom.xml. Otherwise, CI does not even build it.

2025-03-18 07:31 UTC, iluwatar commented
Closed due to inactivity. Thank you for the contribution.

2025-03-18 07:31 UTC, closed without merging