implemented the bloC design pattern issue #2374
iluwatar/java-design-patterns pull request #3128
Opened 2024-12-07 16:33 UTC by darkhyper24

## What problem does this PR solve?

this PR implements the bloc design pattern which is a design pattern used to separate the UI components in dart and flutter from the states logic making the code more maintainable and testable  by following these steps:

1. the UI layer dispatches events like button clicks or user input to the bloc.
2. the bloc processes the events and updates the state accordingly.
3. the state is then emitted to listeners.
4. the listeners concerned with the state then reacts to the state and update the interface accordingly.
Close #2374

2024-12-28 18:45 UTC, darkhyper24 commented
@iluwatar can you please review my pr?

2025-01-11 17:58 UTC, iluwatar requested changes

2025-01-11 17:58 UTC, iluwatar commented on bloC/Readme.md
> +Imagine a simple state-driven system that maintains a counter. Whenever the counter changes, any registered listener receives updates dynamically.
I'm not sure this text belongs in this context

2025-01-11 17:58 UTC, iluwatar commented on bloC/pom.xml
> +    </properties>
Comes from parent pom.xml

2025-01-11 17:58 UTC, iluwatar commented on bloC/pom.xml
> +    </dependencies>
Please add maven-assembly-plugin so that the example can be executed from the command line. See other patterns for examples.

2025-01-11 17:58 UTC, iluwatar commented on bloC/src/main/java/com/iluwatar/bloc/Main.java
> + */
Some more verbosity is needed. Explain the pattern briefly and describe how this code implements it.

2025-01-11 17:58 UTC, iluwatar commented on bloC/src/main/java/com/iluwatar/bloc/State.java
> +public class State {
Consider using record

2025-01-11 17:58 UTC, iluwatar commented on pom.xml
> +      <module>bloC</module>
For consistency, please use small letters only

2025-01-14 18:07 UTC, darkhyper24 commented on bloC/Readme.md
> +Imagine a simple state-driven system that maintains a counter. Whenever the counter changes, any registered listener receives updates dynamically.
i checked the problem in readme file and removed it

2025-01-14 18:07 UTC, darkhyper24 commented on bloC/pom.xml
> +    </properties>
properties section was removed

2025-01-14 18:07 UTC, darkhyper24 commented on bloC/pom.xml
> +    </dependencies>
done

2025-01-14 18:07 UTC, darkhyper24 commented on bloC/src/main/java/com/iluwatar/bloc/Main.java
> + */
some context was added

2025-01-14 18:07 UTC, darkhyper24 commented on bloC/src/main/java/com/iluwatar/bloc/State.java
> +public class State {
done

2025-01-14 19:47 UTC, darkhyper24 commented on pom.xml
> +      <module>bloC</module>
never mind i fixed the conflict

2025-01-14 19:50 UTC, darkhyper24 commented
sorry for the force pushing i had problems with outdated branches and had to recreate the module and delete the previous commits

2025-01-15 20:38 UTC, iluwatar requested changes

2025-01-15 20:38 UTC, iluwatar commented on bloc/Readme.md
> +---
This file should be `README.md`

2025-01-15 20:38 UTC, iluwatar commented on bloc/pom.xml
> +            </plugin>
I think this configuration can be simplified. Take a look at the other patterns for examples.

2025-01-15 21:02 UTC, darkhyper24 commented on bloc/pom.xml
> +            </plugin>
fixed in the last commit

2025-01-15 21:02 UTC, darkhyper24 commented on bloc/Readme.md
> +---
changed the file name in the last commit

2025-01-16 14:56 UTC, iluwatar approved these changes

2025-01-16 14:56 UTC, merged

2025-01-16 14:57 UTC, iluwatar commented
Looks good! Thank you for the contribution 🎉

@all-contributors please add @darkhyper24 for code